Ref cli v2
MoralisWeb3/Moralis-JS-SDK pull request #1009
Opened 2023-02-09 14:24 UTC by Y0moo

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2023-03-01 10:39 UTC, b4rtaz commented on packages/create-moralis-dapp/next/src/template/package.json.tmpl
> +    "axios": "^0.27.2",
Why downgraded?

2023-03-01 11:58 UTC, ErnoW requested changes

2023-03-01 11:58 UTC, ErnoW commented on packages/create-moralis-dapp/next/README.md
> +Run `create-moralis-dapp` in directory where you want to setup dApp
Should this not be `npx create-moralis-dapp`?

2023-03-01 11:58 UTC, ErnoW commented on packages/create-moralis-dapp/toolkit/src/TemplateProcessor.ts
> +  public async normalizeFiles(data?: Answers) {
'normalize' suggests that the content does not change. It suggest that the format/structure only changes. Maybe renaming this to 'process' / 'generate' would be more descriptive.

2023-03-01 11:58 UTC, ErnoW commented on packages/create-moralis-dapp/toolkit/README.md
> +Run `create-moralis-dapp` in directory where you want to setup dApp
This is the readme of the toolkit

2023-03-01 11:58 UTC, ErnoW commented on packages/create-moralis-dapp/toolkit/src/Inquirer.ts
> +  public static get commonQuestions() {
It is currently setup so that we have 1 generator, that is selected by the user, and that generator is responsible for **all** questions, right?

So you slect `nextJs` and then that generator will handle all questions (including the name, apiKey etc.). Would it make more sense to handle the `common` questions in `CMDGenerator`?

Also, it seems that `confirmBeta` is already defined in `CMDGenerator` and again in the `commonQuestions`

2023-03-01 12:47 UTC, Y0moo commented on packages/create-moralis-dapp/next/README.md
> +Run `create-moralis-dapp` in directory where you want to setup dApp
Both works, but will change here to `npx create-moralis-dapp`

Difference:
`npx create-moralis-dapp` will run generator and will install npm package if it's not installed.
`create-moralis-dapp` works only if it's installed on PC

2023-03-01 12:51 UTC, Y0moo commented on packages/create-moralis-dapp/next/src/template/package.json.tmpl
> +    "axios": "^0.27.2",
looks like something from old files... I'll fix

2023-03-01 13:54 UTC, Y0moo commented on packages/create-moralis-dapp/toolkit/src/Inquirer.ts
> +  public static get commonQuestions() {
The current design is each generator is independent. They rely on `@create-moralis-dapp/toolkit`.

This `confirmBeta` duplication is removed on the [[3/3] PR](https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/1011)

But I'll remove it here as well

2023-03-05 22:21 UTC, ErnoW approved these changes

2023-03-05 22:21 UTC, merged