added ESM build to base packages.
MoralisWeb3/Moralis-JS-SDK pull request #1027
Opened 2023-03-07 16:27 UTC by b4rtaz

---
name: added ESM build to base packages.
---

2023-03-09 07:22 UTC, ErnoW requested changes
Overall looks good. Just a few minor questions.

It would be nice to export files seperately for esm, I checked it a bit but also could not see a config to do so. We could use the default `tsc` compiler to generate esm though. It's not a major issue, but would be nice to have if we want to offer code-splitting in the future as well.

2023-03-09 07:22 UTC, ErnoW commented on packages/moralis/package.json
> +  "main": "./lib.esm/index.js",
I think `main` should refer to the cjs build. But it seems that exports takes priority over main since node10 (which is already quite outdated). But it seems best practice to refer to cjs here. https://nodejs.org/api/packages.html#packagejson-and-file-extensions

2023-03-09 07:43 UTC, b4rtaz commented on packages/moralis/package.json
>      "lib.esm/*",
I'll change this to that structure:

```
/lib/esm
/lib/cjs
```

2023-03-09 07:55 UTC, b4rtaz commented on packages/moralis/rollup.config.mjs
> +import typescript from 'rollup-plugin-typescript2';
The main problem with the`tsc` is that, it doesn't support custom extension for output files. I noticed that, the CommonJS bundle **must have** `.cjs` extension. I tried to rename files by script (`node rename.js .js .cjs`) but this is ugly. I think it's better to have one responsible for building.

Basically we have the same approach as axios.

2023-03-09 08:12 UTC, b4rtaz commented on packages/moralis/package.json
> +      },
I've explained this [here](https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/1027#discussion_r1130613254). Basically I've copied the axios approach.

2023-03-09 10:32 UTC, b4rtaz commented
@ErnoW I made a few changes. Now packages have the following structure:

```
/lib/index.d.ts - TypeScript types
/lib/cjs/index.cjs - CommonJS bundle
/lib/esm/index.js - ESM bundle
```

To prevent conflicts with folder names I added the `rollup-plugin-dts` step in rollup configs. It merges .d.ts files into one file.

2023-03-10 01:50 UTC, ErnoW approved these changes

2023-03-10 08:02 UTC, merged