Feature/solana api
MoralisWeb3/Moralis-JS-SDK pull request #129
Opened 2021-11-26 18:22 UTC by sogunshola

---
name: 'Pull request'
about: Solana API implementation
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2021-11-29 12:52 UTC, dani69654 commented on scripts/genSolanaAPI.js
> +  static baseURL = 'https://7f59-41-184-184-103.ngrok.io';
Should this be an ngrok url?

2021-11-29 12:58 UTC, dani69654 commented
I get an error when running the following:

```
await Moralis.SolanaApi.account.balance({
            network: 'mainnet',
            address: 'HKvxPvwjT56Hd2cimR8fLxhuBqgt2Vm6fh2KSJT7XX8F',
})
```

I get:

```
{
    "code": 141,
    "error": "Invalid function: \"sol-balance\""
}
```

2021-12-02 01:30 UTC, ErnoW reviewed
Looks good to me code-wise
It's mostly duplicated from web3Api, so lets keep in mind to abstract this logic next time that we need it (I like to follow the rule to make things generic once you use it 3 times or more 😃 )

Now waiting for the API to be deployed, to test and release it,

2021-12-02 01:30 UTC, ErnoW commented on scripts/genWeb3API.js
> -    }
Why has this been removed?

2021-12-02 01:30 UTC, ErnoW commented on src/Parse.js
> +Moralis.SolanaApi = require('./MoralisSolanaApi').default;
Lets rename this to SolanaAPI to be consistent with Web3API

2021-12-02 07:12 UTC, sogunshola commented on scripts/genWeb3API.js
> -    }
Oh yeah, It was duplicated before, the apiCall() function is called in the fetch() function, so since it's already in the fetch() function, I removed it from the apiCall() function

2021-12-02 07:13 UTC, sogunshola commented on src/Parse.js
> +Moralis.SolanaApi = require('./MoralisSolanaApi').default;
yeahhh. true, I would do that.

2021-12-02 07:15 UTC, sogunshola commented
> Looks good to me code-wise It's mostly duplicated from web3Api, so lets keep in mind to abstract this logic next time that we need it (I like to follow the rule to make things generic once you use it 3 times or more 😃 )
> 
> Now waiting for the API to be deployed, to test and release it,

True, I might as well just abstract it now 😎.. cleaner and shorter code 💪🏾

2022-01-20 08:28 UTC, ErnoW requested changes

2022-01-20 08:28 UTC, ErnoW commented on scripts/genSolanaAPI.js
> +// URL will be changed when api is deployed
```suggestion
```

We can remove this comment

2022-01-20 08:28 UTC, ErnoW commented on scripts/genSolanaAPI.js
> +// };
```suggestion
```

Please remove unused code, instead of commenting out

2022-01-20 08:28 UTC, ErnoW commented on scripts/genSolanaAPI.js
> +  // URL will be changed when api is deployed
```suggestion
```
Remove this comment

2022-01-20 08:28 UTC, ErnoW commented on scripts/genSolanaAPI.js
> +    }
```suggestion
      if (!params.address) {
        params.address = this.Moralis.account;
      }
    }
```

This logic has changed, as we don't have web3.eth anymore

2022-01-20 08:28 UTC, ErnoW commented on scripts/genWeb3API.js
> +// };
```suggestion
```
Remove unused code

2022-01-20 08:28 UTC, ErnoW commented on scripts/generateSolanaApiTypes.js
> +const SWAGGER_PATH = '/api-json';
```suggestion
const API_HOST = 'solana-gateway.moralis.io';
const SWAGGER_PATH = '/api-json';
```
The API_HOST needs to be set

2022-01-20 08:28 UTC, ErnoW commented on src/Parse.js
> +Moralis.SolanaApi = require('./MoralisSolanaApi').default;
Please check, it is still SolanaApi instead of SolanaAPI

2022-01-21 22:47 UTC, merged

2022-01-21 22:50 UTC, ErnoW commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/moralis/v/1.1.0)
- [GitHub release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: