remove node warning in moralis.start
MoralisWeb3/Moralis-JS-SDK pull request #141
Opened 2021-12-08 07:16 UTC by sogunshola

---
name: 'Pull request'
about: Remove info message when using node without moralis secret
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2021-12-08 12:15 UTC, ErnoW requested changes

2021-12-08 12:15 UTC, ErnoW commented on src/Parse.js
> +        // console.warn('Moralis.start warning: to have web3 access, moralisSecret is required');
Remove the code instead of commenting it out.

Also you can convert the `if-else` to an `if` check

2021-12-08 22:45 UTC, sogunshola commented on src/Parse.js
> +        // console.warn('Moralis.start warning: to have web3 access, moralisSecret is required');
👍🏽 great suggestion.

https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/141/commits/6b29197b7297f780ed821802932a978811d4b2a0

done that

2021-12-09 12:12 UTC, ErnoW requested changes

2021-12-09 12:12 UTC, ErnoW commented on src/Parse.js
>        if (!moralisSecret) {
Reverse this check please as it is incorrect now

```suggestion
      if (moralisSecret) {
```

2021-12-13 13:57 UTC, ErnoW approved these changes

2021-12-13 13:57 UTC, merged