Added Enums For Chains
MoralisWeb3/Moralis-JS-SDK pull request #189
Opened 2022-01-12 23:13 UTC by rayyan224

---
Added Enums for Supported chains.
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-01-12 23:15 UTC, ivan-liljeqvist commented
@rayyan224 let's put these chains in a separate file
maybe `Chains.js`

2022-01-12 23:24 UTC, rayyan224 commented
> @rayyan224 let's put these chains in a separate file maybe `Chains.js`

Sure

> @rayyan224 let's put these chains in a separate file maybe `Chains.js`

Ok, np.

2022-01-12 23:45 UTC, ErnoW requested changes

2022-01-12 23:45 UTC, ErnoW commented on types/index.d.ts
> +
```suggestion

  let Chains: IChains;
```

Add this to export the Moralis.Chains type correctly

2022-01-13 00:17 UTC, ErnoW approved these changes

2022-01-13 00:18 UTC, merged

2022-01-17 10:54 UTC, ErnoW commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/moralis/v/1.0.0)
- [GitHub release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: