Feat/web3 auth
MoralisWeb3/Moralis-JS-SDK pull request #243
Opened 2022-02-01 04:11 UTC by rayyan224

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-02-01 12:59 UTC, kantorcodes commented on src/Web3Connector/Web3AuthConnector.js
> +    const { Web3Auth } = require('@web3auth/web3auth');
Why are we using require statements? 😟 😓

2022-02-01 12:59 UTC, kantorcodes commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
Why are we using require statements? 😟 😓

2022-02-01 12:59 UTC, kantorcodes commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
This is really bad practice for keeping bundle sizes small

2022-02-02 10:29 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
At the moment there are no real benefits that we can get, as the SDK is not set up to benefit from tree-shaking. Also in this case we need to load the dependency dynamically (as it's an optional dependency), so using require is logical to use here.

That said, I understand your concern regarding bundle size, and we will work on this in the next major version of the SDK, to make it more modular by using separate packages, and rollup (and probably other tech improvements).

2022-02-02 11:32 UTC, kantorcodes commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
It's possible to benefit from dynamic imports with gulp and babel, see

 https://link.medium.com/ffwfIIIMjnb

Has this approach been tried?

By using require you create tech debt and make tree shaking more and more difficult for each new require statement that is written. Furthermore, I don't believe the variant used in these lines of code is actually dynamic. This is a misconception.

You can use require.ensure to create a chunk instead. Unless you mean the node module is omitted entirely from the bundle during compile process? ( I have no idea how you would reasonably keep track of that, but given the current bundle size I don't believe it's going well.)

https://www.jianshu.com/p/b2dcf4d0e78e

2022-02-02 11:55 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
Yes we tried a similar approach, but without the webpack setup.

But yes, currently the module is omitted from the compiled sdk, and should only be added when the user wants to include this functionality (similar to magic-sdk and walletconnect). But like I mentioned, we will make it its own package in the next release.

Anyway, thanks for the tips and references 🙏 , we will look into it if it is possible with a similar setup by using webpack.

2022-02-02 12:43 UTC, kantorcodes commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
Awesome thank you. 

Another tip, with modern browsers, axios should not be needed, and `fetch` can safely replace all API calls.

2022-02-07 22:23 UTC, ErnoW requested changes

2022-02-07 22:23 UTC, ErnoW commented on src/MoralisWeb3.js
> +      case 'Web3AuthConnector':
lets rename this to web3Auth

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    const { Web3Auth } = require('@web3auth/web3auth');
Similar to walletconnect and magicLink,
This require statement needs to be dynamic. And the `@web3auth/web3auth` dependency needs to be optional. So:
- Wrap it in a try/catch
- Test if you get no error when you build the app and have the dependency not included
- Add this module to `filteredWarnings` in `src/filterConsole.js`

Currently I get an error when building an app without the dependencies. We only want an error to show if the dev actually uses this connector without having the dependency installed. But it should be all optional.

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    const { CHAIN_NAMESPACES, ADAPTER_STATUS } = require('@web3auth/base');
See above comment, same holds for this dependency

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    if (!Web3Auth) {
Also, we had to include something like:
```
WalletConnectProvider = window?.WalletConnectProvider?.default
```
for walletconnect. This was needed to make it work for non-npm-builds, for example if the users imports moralis and this library via a `<script/>` from a CDN provider.
I guess that something similar is also needed in this case.

Please test if it works in a simple app by only using html/js and by using CDN imports via script tags

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +      ticker: 'ETH',
Does this mean that the ticker is always ETH?
So for example also if I use Binance Smart Chain? In that case I would expect it to be BNB.
Would be nice if `web3auth` could determine that on its own. Othewise we would need a mapping for this,

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    }
We don't need the user to provide an infureId link. We can use our own rpc-urls. We can re-use the rpc's from walletconnect in this case:
```
getMoralisRpcs('WalletConnect')[chainIdInDecimals]
```

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    if (!hexChainId) {
Also let the user inut chainId in decimal form.
We can use the `verifyChainId(providedChainId)` for this. This will transform number chainIds to hex

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +    }
The user should not worry about the displayname, only about the chainId.
Would be nice if web3Auth can infer the displayname automatically.
Otherwise we will need to make a mapping for this

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +      const address = (await signer.getAddress()).toLowerCase();
These requests can be in parrallel by using `Promise.all([])`

2022-02-07 22:23 UTC, ErnoW commented on src/Web3Connector/Web3AuthConnector.js
> +  type = 'Web3AuthConnector';
Rename to web3Auth (no need to add "Connector")

2022-02-07 22:23 UTC, ErnoW commented on types/index.d.ts
> +    | 'Web3AuthConnector';
lets rename this to web3Auth

2022-02-08 14:23 UTC, rayyan224 commented on types/index.d.ts
> +    | 'Web3AuthConnector';
sounds good!

2022-02-08 16:33 UTC, rayyan224 commented on src/Web3Connector/Web3AuthConnector.js
> +    }
Yea I like the way u think!

2022-02-09 00:31 UTC, ErnoW approved these changes

2022-02-09 00:32 UTC, merged

2022-02-09 00:52 UTC, ErnoW commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/moralis/v/1.3.0)
- [GitHub release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: