Optimisation/web3api fix
MoralisWeb3/Moralis-JS-SDK pull request #285
Opened 2022-03-11 00:39 UTC by sogunshola

---
name: 'Pull request'
about: When calling web3api the sessionToken is never sent forcing rate limit to always be anonymous. this PR handles that.
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-03-14 11:29 UTC, ErnoW requested changes

2022-03-14 11:29 UTC, ErnoW commented on scripts/genWeb3API.js
> +        const sessionToken = JSON.parse(localStorage.getItem(\`Parse/\${this.appId}/currentUser\`));
We should not ignore the `no-undef` warning. It is possible that localStorage is not defined. For example react-native environment

Can we not use the Moralis or User object (after line 96)?

2022-03-14 11:29 UTC, ErnoW commented on scripts/genWeb3API.js
> +        const installationId = localStorage.getItem(\`Parse/\${this.appId}/installationId\`);
Same as previous comment

2022-03-14 11:29 UTC, ErnoW commented on scripts/genWeb3API.js
> +        const sessionToken = JSON.parse(localStorage.getItem(\`Parse/\${this.appId}/currentUser\`));
Otherwise we should add an extra check if `localStorage` is defined.
Always be as defensive as possible instead of ignoring warnings :)

2022-03-14 11:31 UTC, ErnoW commented on scripts/genWeb3API.js
> +        options._ApplicationId = this.appId
Also, why is the installationId and _ApplicationId needed? In your solution you described we would need the sessionToken. Are these also needed for the rate-limiting?

2022-03-14 12:05 UTC, sogunshola commented on scripts/genWeb3API.js
> +        options._ApplicationId = this.appId
Indeed it is not needed, I just tried to replicate what HttpRequest.request send, but it is not needed for rate limit. I will that out in the next push

2022-03-14 12:06 UTC, sogunshola commented on scripts/genWeb3API.js
> +        const sessionToken = JSON.parse(localStorage.getItem(\`Parse/\${this.appId}/currentUser\`));
👍🏾  I will make those adjustments now. thanks for pointing them out

2022-03-15 15:36 UTC, ErnoW approved these changes

2022-03-15 15:39 UTC, merged