Feat/web3api cursor
MoralisWeb3/Moralis-JS-SDK pull request #319
Opened 2022-04-21 11:19 UTC by sogunshola

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-04-21 13:35 UTC, Capplequoppe commented on scripts/genWeb3API.js
> +        if(params.cursor === result.cursor) {
Should we also have `&& params.cursor !== undefined`?

2022-04-21 13:45 UTC, Capplequoppe commented on scripts/genWeb3API.js
> +    const result = response.data;
I think we can make this more DRY.
What about a helper function like this somewhere; 
```
function getNextOptions(result, options) {
  let nextOptions = options;
  const { result } = response.data;
  if (result.page_size) return options
  if (result.cursor) {
    if (nextOptions.cursor === result.cursor) return [];

    nextOptions.cursor = result.cursor;
  } else {
    if (result.total > (result.page_size * result.page) + 1) {
      nextOptions.offset = (result.page + 1) * (nextOptions.limit || 500);
    }
  }

  return options;
}
```

Then we can just assign the next function like this: 

```
const nextOptions = getNextOptions(result, options)
result.next = () => this.fetchFromServer(name, nextOptions);
```

or

```
const nextOptions = getNextOptions(result, options)
result.next = () => this.fetchFromApi(endpoint, nextOptions);
```

2022-04-21 17:12 UTC, Capplequoppe submitted a review, later dismissed

2022-04-21 17:57 UTC, ErnoW requested changes

2022-04-21 17:57 UTC, ErnoW commented on scripts/genWeb3API.js
> +    if (result.total > (result.page_size * result.page) + 1) {
Shouldn't this be: `result.total > (result.page_size * (result.page + 1))`?

2022-04-21 17:57 UTC, ErnoW commented on scripts/genWeb3API.js
> +    if (result.total > (result.page_size * result.page) + 1) {
We have no check if `result.total` or `result.page` is defined. This is probably the case when result.page_size is defined. But lets add the check to be safe

2022-04-21 17:57 UTC, ErnoW commented on scripts/genWeb3API.js
> +  if (result.cursor && result.cursor !== undefined) {
No need to check for undefined if you check for `result.cursor`

2022-04-21 17:57 UTC, ErnoW commented on scripts/genWeb3API.js
> +    result.next = () => this.fetchFromApi(endpoint, nextOptions);
We don't always want to add a next function. We only want this for paginated requests (so when we use offset or cursor). Please add a conditional check for this.

2022-04-21 18:41 UTC, sogunshola commented on scripts/genWeb3API.js
> +  if (result.cursor && result.cursor !== undefined) {
I agree, but it this was a suggestion from Niclas.

2022-04-25 19:58 UTC, ErnoW commented
Seems to be a use-case where the next() function is added, when it should not. See screenshot:
<img width="348" alt="Screenshot 2022-04-25 at 13 55 29" src="https://user-images.githubusercontent.com/34257502/165164987-f683d75b-6362-41a8-9c75-44503e9eaa04.png">

Also
- Check the linting error
- add the next() function as optional Typescript type

2022-04-25 19:58 UTC, ErnoW commented
Seems to be a use-case where the next() function is added, when it should not. See screenshot:
<img width="348" alt="Screenshot 2022-04-25 at 13 55 29" src="https://user-images.githubusercontent.com/34257502/165164987-f683d75b-6362-41a8-9c75-44503e9eaa04.png">

Also
- Check the linting error
- add the next() function as optional Typescript type

2022-05-02 09:24 UTC, ErnoW approved these changes

2022-05-02 09:24 UTC, merged

2022-05-02 09:45 UTC, ErnoW commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/moralis/v/1.6.0)
- [GitHub release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: