feat(evmApi): resolve api for getNFTMetadata endpoint
MoralisWeb3/Moralis-JS-SDK pull request #340
Opened 2022-05-10 10:47 UTC by sogunshola

---
name: getNFTMetadata
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-05-11 17:27 UTC, ErnoW requested changes

2022-05-11 17:27 UTC, ErnoW commented on packages/evmApi/src/resolvers/token/getNFTMetadata.ts
> +    ...toCamelCase(data),
Change contractType to be an union of all availalbe supported NFT contraact types. I think these are `'ERC721' | 'ERC1155'`

2022-05-11 17:27 UTC, ErnoW commented on packages/evmApi/src/resolvers/token/getNFTMetadata.ts
> +    ...toCamelCase(data),
Cast syncedAt to a Date type (or undefined)

2022-05-20 16:17 UTC, sogunshola commented on packages/evmApi/src/resolvers/token/getNFTMetadata.ts
> +    ...toCamelCase(data),
I will add the contract type union when I improve the PR with the EvmNFT type

2022-05-30 10:44 UTC, merged