Feat(evm api)/server requestand evm sync
MoralisWeb3/Moralis-JS-SDK pull request #392
Opened 2022-05-25 09:02 UTC by sogunshola

---
name: PR handling 3 issues
about: Issues 274 | 273| 248
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-05-25 16:24 UTC, ErnoW commented on demos/test-app-all/src/EvmApi.tsx
> +
Not needed, as we already call Moralis.start in App.tsx

2022-05-25 16:30 UTC, ErnoW commented on demos/test-app-all/src/EvmApi.tsx
>              .then(console.log);
It does not make sense to prefill the user address here.
As the address in this request is refering to the smart contract address
See: https://docs.moralis.io/moralis-dapp/web3-api/native?q=runContractFunction

Can you only prefill the address in requests where it is refering to to the useraddress?

2022-05-25 16:32 UTC, ErnoW commented on packages/evmApi/src/resolvers/Resolver.ts
> +}
I'm missing some context here. What and why is this used for?

2022-05-25 16:40 UTC, ErnoW commented on packages/evmApi/src/resolvers/Resolver.ts
> +    // @ts-ignore TODO: fix type as it should be of type MoralisEvm
These errors can be fixed by extending the type of NetworkModule. If you add `isConnected` as a method in there

2022-05-25 16:43 UTC, ErnoW commented on packages/evmApi/src/resolvers/Resolver.ts
> +  }
We might actually want to resolve default values on implementation, instead of having it generically on ALL requests.

As I mentioned in an earlier comment; for some requests it makes no sense to pre-fill the address with the userAddress (because the address refers to a contract address).

2022-05-25 16:45 UTC, ErnoW commented on packages/evmApi/src/resolvers/Resolver.ts
> +  }
So possibly we could do something like:
```js
export const getTokenPriceResolver = new EvmResolver({
  ...,
  parseParams: (params: Params) => ({
    // -> Here
    chain: resolveDefaultChain(params.chain),
    address: resolveDefaultAddress(params.address),

    exchange: params.exchange,
    to_block: params.toBlock,
    providerUrl: params.providerUrl,
  }),
});

```

That gives us a lot of flexibility, on where and how we want to resolve the address.

2022-05-25 17:34 UTC, sogunshola commented on demos/test-app-all/src/EvmApi.tsx
> +
Disregard, was using to run some tests locally. removing in next push

2022-05-26 09:02 UTC, sogunshola commented on packages/evmApi/src/resolvers/Resolver.ts
> +}
Taking this out. belongs in a separate MR

2022-05-30 08:44 UTC, ErnoW requested changes

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/utils/resolveDefaultParams.ts
> +export const resolveDefaultAddress = (address?: EvmAddressish) => {
It makes more sense to let this function return an EvmAddress instead of a string.
- Better usable in the future
- Corresponds better with the name of this function. We handle any address as an EvmAddress. Unless we are parsing to an output.

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/utils/resolveDefaultParams.ts
> +  const evm = core.modules.getNetwork('evm');
This throws an error if there is no `evm` package registered.

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/utils/resolveDefaultParams.ts
> +    return EvmAddress.create(evm.account).lowercase;
Please enable the `no-else-return` eslint and clean this up: https://eslint.org/docs/rules/no-else-return

We should write better if/else checks that are more readable and maintainable that way.

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/utils/resolveDefaultParams.ts
> +  const evm = core.modules.getNetwork('evm');
This can throw an error if no evm package is installed

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/utils/resolveDefaultParams.ts
> +  return chain ? EvmChain.create(chain).apiHex : undefined;
Lets resolve to eth as default chain

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/resolvers/storage/uploadFolder.ts
> +import { operations } from '../../generated/types';
Should not be part of this PR, as it is submitted in another PR already.

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/resolvers/storage/index.ts
> +export { uploadFolderResolver } from './uploadFolder';
Should not be part of this PR, as it is submitted in another PR already.

2022-05-30 08:44 UTC, ErnoW commented on packages/evmApi/src/resolvers/native/getContractEvents.ts
> +import { EvmChainish, EvmAddress, EvmAddressish } from '@moralisweb3/core';
Should not be part of this PR

2022-05-30 23:31 UTC, merged