feat(testability): improved testability
MoralisWeb3/Moralis-JS-SDK pull request #488
Opened 2022-07-12 13:40 UTC by b4rtaz

---
name: Improved testability
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

2022-07-14 12:20 UTC, ErnoW requested changes

2022-07-14 12:40 UTC, b4rtaz commented on demos/test-app-all/src/Evm.tsx
> +  const evm = Moralis.Evm.connectors.get<MetamaskConnector>(MetamaskConnector.connectorName);
Done.

2022-07-14 12:40 UTC, b4rtaz commented on packages/core/src/Config/Config.ts
> +      throw new Error(`Key "${key.name}" is already registered`);
Done.

2022-07-14 12:44 UTC, b4rtaz commented on packages/core/src/controllers/RequestController.ts
> +    const c = core || MoralisCoreProvider.getDefault();
Done.

2022-07-14 12:46 UTC, b4rtaz commented on packages/evm/src/Connection/Connectors.ts
> +    const core = MoralisCoreProvider.getDefault(); // TODO
Done.

2022-07-14 12:49 UTC, b4rtaz commented on packages/integration/test/evmApi/setup.ts
> +export function setupEnvApi(): MoralisEvmApi {
Done.

2022-07-14 12:49 UTC, b4rtaz commented on packages/core/src/Config/Config.ts
> +  private readonly items = new Map<string, ConfigItem<any>>();
Done.

2022-07-14 12:54 UTC, b4rtaz commented on packages/core/src/Config/Config.ts
> +          message: `Key "${keyOrName}" is unregistered. Did you forget to register some module?`,
A better message would be: `Have you registered all required modules?`. Here I throw this error, when an user tries to set a unregistered key. 

```ts
        throw new MoralisCoreError({
          code: CoreErrorCode.CONFIG_KEY_NOT_EXIST,
          message: `Key "${keyOrName}" is unregistered. Have you registered all required modules?`,
        });
```

2022-07-14 15:19 UTC, ErnoW commented on demos/test-app-all/src/Core.tsx
> +      Moralis.Core.registerModules([EvmApi]);
Ah yes I see now, it is because we are using the umbrella package anyway in the test app, and it is referencing to the same moralis instance. 👍

2022-07-14 15:23 UTC, ErnoW commented on packages/core/src/Config/Config.ts
> +          message: `Key "${keyOrName}" is unregistered. Did you forget to register some module?`,
Or is this because most configs are being registered during the setup of all modules, and that's why this error occurs when the corresponding module is not being registered?

2022-07-14 15:52 UTC, b4rtaz commented on packages/core/src/Config/Config.ts
> +          message: `Key "${keyOrName}" is unregistered. Did you forget to register some module?`,
This error occurs when a user tries to set some config key, but a module is not registered (and keys are not registered). For example:

```js
const core = MoralisCore.create(); // registries 'logLevel', 'appId', ... keys
core.config.set('logLevel', 'info'); // OK

core.config.set('apiKey', 'x'); // throws the `Key "apiKey" is unregistered". Have you registered all required modules?` error!

core.registerModule(MoralisEvmApi); // registries the 'apiKey' key

core.config.set('apiKey', 'x'); // OK
```

2022-07-18 13:32 UTC, ErnoW approved these changes

2022-07-18 13:32 UTC, merged