test(core): test coverage for EvmTransactionResponse
MoralisWeb3/Moralis-JS-SDK pull request #489
Opened 2022-07-12 19:20 UTC by sogunshola

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-07-13 06:39 UTC, b4rtaz commented on packages/core/src/test/EvmTransactionResponse.test.ts
> +// Set variables
Should this comment be below the import section?

2022-07-13 06:40 UTC, b4rtaz commented on packages/core/src/test/EvmTransactionResponse.test.ts
> +    expect(result.to).toBe(inputWithAllData.to);
in this place, I think we need more expectations.

2022-07-13 10:21 UTC, ErnoW requested changes
Nice work, please add more coverage for the equality tests.
Also the wait function is not covered.

run `yarn test:coverage` in the core package to get a coverage report.

2022-07-13 10:21 UTC, ErnoW commented on packages/core/src/test/EvmTransactionResponse.test.ts
> +  });
Can you add more cases for equality checks?
If you run `yarn test:coverage` then you can see line coverage. Some cases are not yet included in the unit tests

2022-08-03 08:13 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmTransactionResponse/EvmTransactionResponse.test.ts
> +  });
It this necessary?

2022-08-03 08:26 UTC, sogunshola commented on packages/evmUtils/src/dataTypes/EvmTransactionResponse/EvmTransactionResponse.test.ts
> +  });
Yes. the module has to be registered first. That's the case in all tests for evmUtils

2022-08-03 10:00 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmTransactionResponse/EvmTransactionResponse.test.ts
> +  });
But you don't test the module here. You test just only one class without a reference to modules. If the module setup is not necessary to test the class, you shouldn't call it. Tests should touch only minimal region of the code.

2022-08-03 10:21 UTC, b4rtaz approved these changes

2022-08-03 10:22 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmTransactionResponse/EvmTransactionResponse.test.ts
> +  });
After @sogunshola feedback: this setup is necessary.

2022-08-03 10:34 UTC, b4rtaz approved these changes

2022-08-16 07:45 UTC, closed without merging