Move evm logic to evm utils
MoralisWeb3/Moralis-JS-SDK pull request #521
Opened 2022-07-21 19:29 UTC by ErnoW

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

- Moved all Evm dataTypes to `evm-utils`
- Moved register of config of `formatEvmAddress` and `formatEvmChainId` to `evm-utils`
- Moved register of config of `defaultEvmApiChain` to `evm-api`

Other fixes/improvements
- Naming of `setupEvmApi`
- Config of eslint was broken (syntax error)
- Fixed versioning of newly created packages
- cache format function in nx

2022-07-22 07:47 UTC, b4rtaz requested changes
Just 3 remarks. Good job.

2022-07-22 07:47 UTC, b4rtaz commented on packages/core/package.json
>      "@ethersproject/units": "^5.6.0",
Do we need these dependencies?

2022-07-22 07:47 UTC, b4rtaz commented on packages/evmUtils/src/config/EvmUtilsConfigSetup.ts
> +      config.registerKey(EvmUtilsConfig.formatEvmChainId);
I think this approach is wrong. This approach hides modules usage errors. You should get an error, if you use the module system in wrong way.

2022-07-22 07:47 UTC, b4rtaz commented on packages/evmUtils/src/test/setup.ts
> +export const setupEvm = () => {
Should be `setupEvmUtils()`.

2022-07-25 09:41 UTC, ErnoW commented on packages/core/package.json
>      "@ethersproject/units": "^5.6.0",
Only as long as it is being used by the Sol datatypes in core.

2022-07-25 10:06 UTC, b4rtaz approved these changes

2022-07-25 10:08 UTC, merged