feat(demo): supabase demo
MoralisWeb3/Moralis-JS-SDK pull request #546
Opened 2022-08-01 10:14 UTC by sogunshola

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-08-08 06:16 UTC, b4rtaz requested changes

2022-08-08 06:16 UTC, b4rtaz commented on demos/demo-supabase-auth/src/auth/MoralisAuthAdapter.ts
> +      // @ts-ignore (see note at top of file)
I don't see any note at top.

2022-08-08 11:05 UTC, ErnoW requested changes

2022-08-08 11:05 UTC, ErnoW commented on demos/demo-supabase-auth/src/auth/MoralisAuthAdapter.ts
> +      throw new Parse.Error(Parse.Error.OBJECT_NOT_FOUND, 'Moralis auth failed, invalid data');
There is no Parse is this project.

Is this auth-adapter used in this demo, as this file was specifically needed in the parse-server demo.

2022-08-08 11:05 UTC, ErnoW commented on demos/demo-supabase-auth/src/auth/authService.ts
> +export async function verifyMessage({ network, signature, message }: VerifyMessage) {
Where are we actually verifying the signature, that is not clear to me

2022-08-08 11:05 UTC, ErnoW commented on demos/demo-supabase-auth/src/middlewares/errorHandler.ts
> +        // Handle ParseError
We have no ParseErrors in this project

2022-08-08 12:02 UTC, sogunshola commented on .changeset/slow-feet-tell.md
> +'demo-subabase-auth': major
Yes this helps.. thanks for this

2022-08-16 08:22 UTC, ErnoW approved these changes

2022-08-16 12:30 UTC, merged