feat: add tracking for api calls
MoralisWeb3/Moralis-JS-SDK pull request #550
Opened 2022-08-02 17:18 UTC by ErnoW

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-08-02 19:19 UTC, b4rtaz requested changes

2022-08-02 19:19 UTC, b4rtaz commented on packages/core/src/MoralisCore.ts
> +  public readonly libVersion = LIB_VERSION;
This could be `static`.

2022-08-02 19:19 UTC, b4rtaz commented on packages/apiUtils/src/resolvers/getCommonHeaders.ts
> +  'x-moralis-platform-version': libVersion,
If `Core.libVersion` would be `static`, here you don't need to pass `libVersion`.

2022-08-03 07:42 UTC, b4rtaz requested changes

2022-08-03 07:42 UTC, b4rtaz commented on packages/apiUtils/src/resolvers/EndpointResolver.test.ts
> +      }
It's better to use `expect()` to assert in tests. It doesn't matter that, that expectation is inside in a mock implementation.

```
expect(options.headers['x-moralis-platform-version']).toBe(MoralisCore.libVersion);
...
```

2022-08-03 07:47 UTC, b4rtaz requested changes

2022-08-03 07:47 UTC, b4rtaz commented on packages/apiUtils/src/resolvers/EndpointResolver.test.ts
> +    expect(response).toBeDefined();
Here you need `expect(mockRequest).toHaveBeenCalledTimes(1);`. Because you want to prove that, asserts in the mock function was called. Currently this test may pass, without asserts in the mock function.

2022-08-03 08:34 UTC, ErnoW commented on packages/apiUtils/src/resolvers/EndpointResolver.test.ts
> +      }
It might be more difficult to read, as I prefer to use the arrange-act-assert method.

I'll try a different solution

2022-08-03 08:42 UTC, merged