Feat/express proxy
MoralisWeb3/Moralis-JS-SDK pull request #567
Opened 2022-08-09 19:37 UTC by sogunshola

---
name: Express app api proxy using axios
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-08-09 20:20 UTC, b4rtaz requested changes

2022-08-09 20:20 UTC, b4rtaz commented on demos/parse-server/src/api/evmProxy.ts
> +  evmProxyRouter.route(`/${descriptor.name}`).post(async (req, res) => {
I think here you could put `.urlPattern` as an argument of the `.route(...)` method. **In this way, the proxy would have the same URL patterns as Moralis API has.**

```js
for (const descriptor of descriptors) {

  async function requestHandler(req, res) {
    // ...
  }
  const urlPattern = descriptor.urlPattern.replace(/\{/g, ':').replace(/\}/g, ''); // This converts an "universal" route format to express.js format.
  const routeBuilder = router.route('proxy' + urlPattern);
  switch (descriptor.method) {
    case 'get':
      routeBuilder.get(requestHandler);
      break;
     case 'post':
      routeBuilder.post(requestHandler);
      break;
}
```

<pre>
https://x.com/proxy/<strong>account/{network}/{address}/balance</strong>
https://x.com/proxy/<strong>account/{network}/{address}/nft</strong>
...
</pre>

We should keep the same type of methods here (GET, POST).

2022-08-09 20:30 UTC, b4rtaz requested changes

2022-08-09 20:30 UTC, b4rtaz commented on demos/parse-server/public/script.js
> +  handleEvmProxyCall('web3ApiVersion');
After [this](https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/567/files#r941763742) remarks, here should be `handleEvmProxyCall('GET', 'web3/version');`.

2022-08-09 20:30 UTC, b4rtaz commented on demos/parse-server/public/script.js
> +  handleEvmProxyCall('getNativeBalance', {
After [this](https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/567/files#r941763742) remarks, here should be `handleEvmProxyCall('GET', 'info/endpointWeights');`.

2022-08-09 20:33 UTC, b4rtaz requested changes

2022-08-09 20:33 UTC, b4rtaz commented on demos/parse-server/src/api/evmProxy.ts
> +export default evmProxyRouter;
Maybe this router should be in the own package (`@moralisweb3/expressjs`)? Because this logic would be exactly the same for the parse-server.

2022-08-09 20:38 UTC, b4rtaz requested changes

2022-08-09 20:38 UTC, b4rtaz commented on demos/parse-server/src/apiRouter.ts
> +apiRouter.use('/evm-proxy', evmProxyRouter);
`/evm-proxy` -> `/evm-api-proxy`

2022-08-09 20:40 UTC, b4rtaz commented
Sorry for multiple requests. I've already finished. 😄

2022-08-15 12:50 UTC, b4rtaz commented
I think the below files:

```
demos/express-proxy/src/api/*
demos/express-proxy/src/apiRouter.ts
demos/express-proxy/src/middlewares/*
```

You can extract to own package: `@moralisweb3/express`. The demo app will use this package.

By this, you can easily attach proxy to `demos/express-proxy` and `demos/parse-server` and keep the code in single place.

2022-08-15 12:50 UTC, b4rtaz requested changes

2022-08-15 12:51 UTC, sogunshola commented on demos/express-proxy/src/api/solanaProxy.ts
> +export default solanaProxyRouter;
Nice idea, will do that

2022-08-16 15:33 UTC, ErnoW requested changes

2022-08-16 15:33 UTC, ErnoW commented on demos/express/package.json
> +  "name": "@moralisweb3/express",
Similar to what we did with the firebase demo: lets not create a separate package to create proxies. We need to have a generic package that can be used for any backend that creates procies. As this approach will result in maintaining a large amount of integrations that are very opinionated (devs might want to implement their own systems, so we need to be flexible).

2022-08-16 15:33 UTC, ErnoW commented on demos/express/src/middlewares/rateLimiter.ts
> +import { createClient } from 'redis';
For a simple express demo I would say that rate-limiting is a bit much, and we could keep it as simple as possible.

For the parse-demo we should include it for sure I would say. As we can use that demo to migrate people over from v1 to a self hosted parse-server in v2

2022-08-17 07:04 UTC, sogunshola commented on demos/express/package.json
> +  "name": "@moralisweb3/express",
👍🏾 Included the proxy generator in proxy package now

2022-08-17 13:07 UTC, b4rtaz commented on demos/express/src/middlewares/rateLimiter.ts
> +import { createClient } from 'redis';
I found the [express-rate-limit](https://github.com/nfriedly/express-rate-limit) package. It looks like easy to use and it doesn't require redis. By default it uses the memory store.

2022-08-19 09:28 UTC, ErnoW commented
Currently I see references to both `redis` and `express-rate-limit`. 
Can we only use express-rate-limit in this demo?

2022-08-19 09:28 UTC, ErnoW commented
Other than that, this demo looks good to me

2022-08-22 08:39 UTC, b4rtaz approved these changes

2022-08-22 08:48 UTC, b4rtaz requested changes
We need the `express-rate-limit` package instead pure redis.

2022-08-22 10:31 UTC, b4rtaz commented on demos/parse-server/.env.example
> +REDIS_URL='redis://localhost:6379'
Is this still needed (`REDIS_URL`)?

2022-08-22 10:34 UTC, sogunshola commented on demos/parse-server/.env.example
> +REDIS_URL='redis://localhost:6379'
No. I just removed it

2022-08-22 10:42 UTC, b4rtaz approved these changes

2022-08-22 11:29 UTC, ErnoW approved these changes

2022-08-22 11:29 UTC, merged