Prettier fixes
MoralisWeb3/Moralis-JS-SDK pull request #591
Opened 2022-08-18 12:34 UTC by ErnoW

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description
- Nested prettierignore files do not work properly with Vscode and thus was conflicting (local formatting vs CI check)
- Inconsistencies in some demo apps regarding formatting have been removed (now we only use the prettier root)
- Removed some eslint rules for the firebase app as it was conflicting with formatting rules. We will create a eslint rule-set that we will use in all the demo apps as well

2022-08-18 13:17 UTC, b4rtaz requested changes

2022-08-18 13:17 UTC, b4rtaz commented on demos/firebase-auth/functions/package.json
> -    "eslint-plugin-import": "^2.25.4",
I think this is not the best approach. **By this we give users a demo with no eslint**. After I copy the demo folder to my local machine, I have a nice demo but eslint doesn't work. So we don't provide the best programming practices. I believe that, some users will build an own product on this demo.

```
b4rtaz@macbook functions % npm run lint

> firebase-auth-functions@1.0.0 lint
> eslint --ext .js,.ts .


Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    npm init @eslint/config
```

2022-08-18 13:32 UTC, b4rtaz commented on demos/firebase-auth/functions/package.json
> -    "eslint-plugin-import": "^2.25.4",
Basically the `<root_of_repo>/.eslintrc.js` file has only 1 393 bytes, we could duplicate it be each demo. So that means, we should have one `.eslintrc.js` for SDK packages, and many `.eslintrc.js` for each demo.

2022-08-18 14:23 UTC, ErnoW commented on demos/firebase-auth/functions/package.json
> -    "eslint-plugin-import": "^2.25.4",
What I want to do is create a new package that contains the eslint rules, that way we can have an eslintrc in every project as well, that is conform with our own lint styling. Users can then easily opt-out or change the rules.

I removed it for now, as it was conflicting with prettier. But I do agree that we need a simple eslint in every project

2022-08-20 13:17 UTC, ErnoW commented on demos/firebase-auth/functions/package.json
> -    "eslint-plugin-import": "^2.25.4",
This is now fixed with the introduction of the eslintConfig package

2022-08-20 15:07 UTC, b4rtaz requested changes

2022-08-20 15:07 UTC, b4rtaz commented on packages/core/src/controllers/AxiosRetry.ts
> +        // TODO: refactor to fix this error
I think here refactor is NOT necessary. This rule refers to cases where you can put all promises into `Promise.all()`.

> When Not To Use It
> 
> In many cases the iterations of a loop are not actually independent of each-other. For example, the output of one iteration might be used as the input to another.

Source: https://eslint.org/docs/latest/rules/no-await-in-loop#when-not-to-use-it

2022-08-22 11:33 UTC, ErnoW commented on packages/core/src/controllers/AxiosRetry.ts
> +        // TODO: refactor to fix this error
Ah yes you're right, it does not apply in this situation

2022-08-25 07:50 UTC, merged