chore: add separate eslint package
MoralisWeb3/Moralis-JS-SDK pull request #596
Opened 2022-08-18 22:41 UTC by ErnoW

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

- Move eslint rules to separate package
- Add common rules (based on google and airbnb preset without too much opinionated rules)
- Include this ruleset in all packages and demo projects

2022-08-19 08:13 UTC, b4rtaz commented
Just one remark. The rest looks fine.

2022-08-19 08:13 UTC, b4rtaz requested changes

2022-08-19 08:13 UTC, b4rtaz commented on packages/eslint/README.md
> +# @moralisweb3/eslint-config
I think the name of this directory is not consistent. The package is `eslint-config`, the directory is `eslint`. Should be `eslintConfig`.

`packages/eslintConfig/README.md`

2022-08-19 08:16 UTC, sogunshola submitted a review, later dismissed
Looks good

2022-08-19 08:27 UTC, b4rtaz commented
`This branch has conflicts that must be resolved`

2022-08-20 08:47 UTC, b4rtaz approved these changes

2022-08-20 08:47 UTC, merged