add missing @moralisweb3/sol-utils dependency to core
MoralisWeb3/Moralis-JS-SDK pull request #609
Opened 2022-08-24 10:27 UTC by meseta

---
name: 'add missing @moralisweb3/sol-api dependency to core'
about: index.ts imports @moralisweb3/sol-utils in index.ts, but it's not listed as a dependency
---

### Checklist

- [ x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ x] I have made corresponding changes to the documentation
- [ x] I have updated Typescript definitions when needed

### Issue Description

index.ts imports @moralisweb3/sol-utils in index.ts, but it's not listed as a dependency

### Solution Description

add @moralisweb3/sol-utils to dependency

2022-08-24 11:16 UTC, b4rtaz approved these changes
Thanks for this PR!

2022-08-24 11:19 UTC, b4rtaz requested changes
Prettier didn't pass.

```
Checking formatting...
[warn] package.json
[warn] Code style issues found in the above file. Forgot to run Prettier?
error Command failed with exit code 1.
```

You need to call `yarn format` in the root of this repository and commit changes.

2022-08-25 08:02 UTC, ErnoW approved these changes

2022-08-25 08:02 UTC, merged

2022-08-25 08:03 UTC, ErnoW commented
Fixed the prettier warning, thanks for the contribution!