docs: EvmChain
MoralisWeb3/Moralis-JS-SDK pull request #616
Opened 2022-08-25 14:22 UTC by sogunshola

add technical docs for EvmChain

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-08-26 08:22 UTC, ErnoW requested changes

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * const chain = EvmChain.create(1)
Lets add also an example with hex decimal string as input here

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * ```ts
Does it work better when we specify `ts` here? 🤔

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +  // Getter to return _chainlistData and throws an error if it is not defined
Why remove the code-block here?

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * EvmChain.equals("0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359", "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359")
These are not chains

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * @example chain.display() // "Ethereum"
Don't think this is true, as it returns the hex as well (and name can be null)

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +  getExplorerPath(value: { block: string } | { transaction: string } | { account: string } | { erc20: string }) {
Add description for this function as well

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * @example chain.currency // "ETH"
Please check the typescript definition, the return type is different (and can  be undefined as well)

2022-08-26 08:22 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
>    }
All static getters / enums, should be at the top. Like we have in EvmAddress.
I just updated this in our internal docs, as I forgot to mention this.

2022-08-29 07:18 UTC, sogunshola commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * ```ts
I think so. because it a `.md` file now, when I preview it without ```ts I get a black and white code block

2022-08-29 07:21 UTC, sogunshola commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +  // Getter to return _chainlistData and throws an error if it is not defined
It's a private function and I am not sure if we want to document private functions. Do we? 🤔

2022-08-29 11:35 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +  // Getter to return _chainlistData and throws an error if it is not defined
I think no.

2022-08-30 09:27 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +  // Getter to return _chainlistData and throws an error if it is not defined
It should not display in the docs as we have this setup. Only public methods should be documented:
```
  "visibilityFilters": {
    "protected": false,
    "private": false,
    "inherited": false,
    "external": false,
    "@alpha": false,
    "@beta": false
  },
```

But if we add a comment to a function, class etc, then lets keep it in a uniform style with code-blocks. As this makes it easier to refactor to public (if needed later on), or other integrations as the vscode autocomplete.

2022-08-30 09:40 UTC, ErnoW requested changes

2022-08-30 09:40 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> + * @example "3"
```suggestion
 * @example 3
```
Should not be a string

2022-08-30 09:40 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
> +   * @example chain.display() // "Ethereum 0x1" | "0x1"
```suggestion
   * @example chain.display() // "Ethereum (0x1)" | "0x1"
```

2022-09-01 15:47 UTC, merged