docs: Erc20Token
MoralisWeb3/Moralis-JS-SDK pull request #617
Opened 2022-08-25 17:31 UTC by sogunshola

technical docs for ERC20 token

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-08-26 08:28 UTC, ErnoW requested changes

2022-08-26 08:28 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
> +   * @param value - the Erc20Tokenish type
Please link to Erc20Tokenish, with {@link } (I think that should work)

2022-08-26 08:28 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
> +   * Compares two Erc20Token instances
Add information that we do equality check based on contractAddress and the chain

2022-08-26 08:28 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
> +  toJSON() {
Missing docs

2022-08-26 08:28 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
> +   * Returns the name of the token.
I think you can use `@returns the name of the token here`

2022-08-26 08:28 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
> +   * Returns the name of the token.
Also in these cases add a comment with example of the output

2022-08-27 06:50 UTC, sogunshola commented on packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
> +   * @param value - the Erc20Tokenish type
The @param decorator already links the params type
<img width="450" alt="Screenshot 2022-08-27 at 07 49 59" src="https://user-images.githubusercontent.com/41871548/187018687-0a7320e9-98b5-47f4-a891-8211de51c84b.png">

2022-08-30 09:42 UTC, ErnoW approved these changes

2022-08-30 09:42 UTC, merged