refactor:adding chainId check in EvmTransactionLog
MoralisWeb3/Moralis-JS-SDK pull request #666
Opened 2022-09-10 14:44 UTC by 3scava1i3r

---
name: 'Better equality check for EvmTransactionLog, it should also check for chainId'
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-09-13 20:16 UTC, b4rtaz requested changes

2022-09-13 20:16 UTC, b4rtaz commented on .changeset/thick-pugs-live.md
> +'@moralisweb3/evm-utils': major
Should be `patch`.

2022-09-13 20:41 UTC, 3scava1i3r commented on .changeset/thick-pugs-live.md
> +'@moralisweb3/evm-utils': major
changed the same

2022-09-14 09:01 UTC, b4rtaz approved these changes

2022-09-15 12:05 UTC, ErnoW requested changes
Please check the pipelines there are some issues:
- small formatting issues. Make sure you have prettier installed as extention in your editor. Or run `yarn format`
- The places where `EvmTransactionLog` are implemented (in the evmApi) should provide the chainId to the `EvmTransactionLog`

2022-09-15 12:09 UTC, 3scava1i3r commented
Will do,also i found an issue with EVMTXNReceipt but was not able to find the same,do you mind pointing me to that

2022-09-16 15:07 UTC, ErnoW commented
> EVMTXNReceipt

The EvmTransactionReceipt has been removed, we now only use EvmTransactionResponse.
(Previously we had a difference between a receipt and response, but now we have all the data in EvmTransactionResponse)

2022-09-18 17:08 UTC, 3scava1i3r commented
@ErnoW an issue that i encountered was the evmTransactionlogish is imported from node_modules evmUtils which is not updated with `chainId` therefore it produces the error of 

`Object literal may only specify known properties, and 'chainId' does not exist in type 'EvmTransactionLogish'.`
I'd appreciate any help here

2022-10-19 09:11 UTC, ErnoW commented
Fixed some small issues and moved to https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/762 as I cannot push to this branch

2022-10-19 09:11 UTC, closed without merging