Feat: Add SolApi.token.getTokenPrice
MoralisWeb3/Moralis-JS-SDK pull request #670
Opened 2022-09-13 18:08 UTC by 3scava1i3r

---
name: 'Add SolApi.token.getTokenPrice'
about: the 
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

We have the solApi endpoint with this as an option and still did not have the same in SDK

### Solution Description

Added getPrice endpoint support under Solana API in JS-SDK

2022-09-14 08:11 UTC, sogunshola commented on packages/solApi/tsconfig.json
> +  "include": ["src/**/*", "types/**/*", "getTokenPrice.ts"]
Why do we have this file name included separately?

2022-09-14 08:13 UTC, sogunshola commented on packages/solApi/src/resolvers/token/getTokenPrice.ts
> +        exchangeAddress: data.exchangeAddress,
This should be casted to SolAddress datatype, check implementation here https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/7a8d21de93e5ce381e6ef4046d08e70feb7390ca/packages/solApi/src/resolvers/account/getNFTs.ts#L33

2022-09-14 08:14 UTC, sogunshola commented on packages/solApi/src/resolvers/token/getTokenPrice.ts
> +        exchangeAddress: data.exchangeAddress,
This should be casted to SolAddress datatype, check implementation here https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/7a8d21de93e5ce381e6ef4046d08e70feb7390ca/packages/solApi/src/resolvers/account/getNFTs.ts#L33

2022-09-14 08:18 UTC, sogunshola commented on packages/solApi/src/resolvers/token/getTokenPrice.ts
> +          value: data.nativePrice.value,
This also should be casted to SolNative datatype. 

see the implementation here https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/7a8d21de93e5ce381e6ef4046d08e70feb7390ca/packages/solApi/src/resolvers/account/getSPL.ts#L35

2022-09-14 08:19 UTC, sogunshola requested changes
Left a few comments

2022-09-14 10:49 UTC, 3scava1i3r commented on packages/solApi/tsconfig.json
> +  "include": ["src/**/*", "types/**/*", "getTokenPrice.ts"]
must be a minute error

2022-09-14 11:35 UTC, 3scava1i3r commented on packages/solApi/src/resolvers/token/getTokenPrice.ts
> +          value: data.nativePrice.value,
changes made

2022-09-14 11:35 UTC, 3scava1i3r commented on packages/solApi/src/resolvers/token/getTokenPrice.ts
> +        exchangeAddress: data.exchangeAddress,
changes made

2022-09-14 12:08 UTC, sogunshola reviewed
LGTM, @ErnoW please take a look when you have a moment

2022-09-14 14:47 UTC, sogunshola reviewed
please run `yarn format` so that prettier error will be corrected.

2022-09-15 19:42 UTC, sogunshola approved these changes

2022-09-15 19:42 UTC, merged