fix: support not defined contractType for NFT types.
MoralisWeb3/Moralis-JS-SDK pull request #673
Opened 2022-09-15 08:43 UTC by b4rtaz

---
name: [support not defined contractType for NFT types.](https://github.com/MoralisWeb3/Moralis-JS-SDK/commit/1ec4c2fe3003ab6a2e10a6ee5825145fd6d698ea)
---

2022-09-16 14:53 UTC, ErnoW requested changes

2022-09-16 14:53 UTC, ErnoW commented on packages/evmUtils/src/dataTypes/EvmNft/EvmNft.ts
> +    contractType: noramlizeEvmNftContractType(data.contractType),
Could we not just something like:
```
    contractType: maybe(data.contractType, validateValidEvmContractType),
```

2022-09-16 16:50 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmNft/EvmNft.ts
> +    contractType: noramlizeEvmNftContractType(data.contractType),
In the previous version here's also a validation. I didn't change it.
https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/packages/evmUtils/src/dataTypes/EvmNftContractType.ts

2022-09-16 16:51 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmNft/EvmNft.ts
> +    contractType: noramlizeEvmNftContractType(data.contractType),
Maybe it's not needed.

2022-09-21 10:04 UTC, b4rtaz commented on packages/evmUtils/src/dataTypes/EvmNft/EvmNft.ts
> +    contractType: noramlizeEvmNftContractType(data.contractType),
I've standardized the code.

```js
contractType: maybe(data.contractType, normalizeEvmNftContractType),
```

2022-09-22 09:32 UTC, ErnoW approved these changes

2022-09-22 09:32 UTC, merged