feat(stream): add verify signature function
MoralisWeb3/Moralis-JS-SDK pull request #674
Opened 2022-09-15 13:48 UTC by sogunshola

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-09-15 13:53 UTC, ErnoW requested changes

2022-09-15 13:53 UTC, ErnoW commented on packages/streams/src/MoralisStreams.ts
> +  };
To clean up the code, I think all the logic can be moved to the 'methods' folder and we call it here like

`public readonly verifySignature = (options: VerifySignatureOptions) => makeVerifySignature(this.core)(options)`

2022-09-15 13:53 UTC, ErnoW commented on packages/streams/src/resolvers/readSettings.ts
> -const name = 'ReadSettings';
Also rename this file

2022-09-15 13:53 UTC, ErnoW commented on packages/streams/src/utils/verifySignature.ts
> +export const verifySignature = ({ body, signature }: VerifySignatureOptions, apiKey: string): boolean => {
Like mentioned above, lets move it to /methods

2022-09-16 08:28 UTC, b4rtaz submitted a review, later dismissed

2022-09-16 09:00 UTC, b4rtaz submitted a review, later dismissed

2022-09-16 09:15 UTC, b4rtaz approved these changes

2022-09-16 09:15 UTC, merged