moralis auth firebase extension + demo. poc.
MoralisWeb3/Moralis-JS-SDK pull request #676
Opened 2022-09-16 11:43 UTC by b4rtaz

---
name: moralis auth firebase extension + demo. POC.
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

2022-09-20 20:49 UTC, ErnoW requested changes

2022-09-20 20:49 UTC, ErnoW commented on .changeset/shaggy-pears-poke.md
> +The first release of the package.
```suggestion
Add client package for firebase authentication.
```

2022-09-20 20:49 UTC, ErnoW commented on .github/workflows/main.yml
> +          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}_C6
I never encountered the need for changing these, what errors do you get when you need to update the caching? we probably need a better system for this.

For now this works okay, but please update also in `docs.yml` as it shares the same cache

2022-09-20 20:49 UTC, ErnoW commented on packages/clientFirebaseAuth/package.json
> +    "lint": "eslint . --ext .js,.ts,.tsx,jsx",
Add `format` script

2022-09-20 20:49 UTC, ErnoW commented on packages/clientFirebaseAuth/src/requestChallenge.ts
> +}
Lets rename to requesMessage instead to ensure consistency with the Auth product and SDL

2022-09-20 20:49 UTC, ErnoW commented on packages/clientFirebaseAuth/src/requestChallenge.ts
> +}
Does it make sense to have 1 function `requestMessage`, just like we have in the sdk? And let it accept a `network` param? Then we can check on the provided network (if one is provided, otherwise default to 'evm')

2022-09-21 07:49 UTC, b4rtaz commented on .github/workflows/main.yml
> +          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}_C6
This happens every time when I add a new package. [Details](https://github.com/MoralisWeb3/Moralis-JS-SDK/actions/runs/3083132566/jobs/4983702911).

2022-09-21 07:52 UTC, b4rtaz commented on packages/clientFirebaseAuth/package.json
> +    "lint": "eslint . --ext .js,.ts,.tsx,jsx",
We don't have the `format` script anymore. For example: [auth](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/packages/auth/package.json), [evmApi](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/packages/evmApi/package.json).

2022-09-21 07:53 UTC, b4rtaz commented on packages/clientFirebaseAuth/package.json
> +    "lint": "eslint . --ext .js,.ts,.tsx,jsx",
We have the `format` script in the root package.json only.

2022-09-21 08:42 UTC, b4rtaz commented on packages/clientFirebaseAuth/src/requestChallenge.ts
> +}
I think the default `networkType` parameter is risky. Because this forces another required parameters. [I've changed](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/feat/firebase-auth-extension/packages/clientFirebaseAuth/src/requestMessage.ts) to a similar approach like in the /auth package:

```ts
RequestEvmMessageParams | RequestSolanaMessageParams
```

2022-09-21 14:39 UTC, ErnoW commented on packages/clientFirebaseAuth/package.json
> +    "lint": "eslint . --ext .js,.ts,.tsx,jsx",
Ah my bad. You're right

2022-09-21 14:47 UTC, ErnoW commented on packages/clientFirebaseAuth/src/requestChallenge.ts
> +}
Yes this seems perfect

2022-09-21 14:49 UTC, ErnoW commented on demos/firebase-auth-ext/firebase.json
> +}
When I create this file I get additional properties, should those not be included?:
```
  "extensions": {
    "moralis-auth": "moralis/moralis-auth@0.1.2"
  }
```

```
  "emulators": {
    "functions": {
      "port": 5001
    },
    "hosting": {
      "port": 5002
    },
    "ui": {
      "enabled": true
    }
  },
```

2022-09-21 17:50 UTC, ErnoW commented on demos/firebase-auth-ext/firebase.json
> +}
Yeah now that I see how extensions work in the project, it makes sense to not include it in the json. Seems good.

2022-09-21 20:39 UTC, ErnoW approved these changes

2022-09-21 20:39 UTC, merged