serialization tests for operations.
MoralisWeb3/Moralis-JS-SDK pull request #775
Opened 2022-10-25 13:46 UTC by b4rtaz

---
name: serialization tests for operations.
---

2022-10-25 14:13 UTC, ErnoW requested changes

2022-10-25 14:13 UTC, ErnoW commented on packages/common/evmUtils/src/operations/token/getWalletTokenTransfersOperation.ts
> +    address: EvmAddress.create(request.address, core).checksum,
Should be lowercase. Most of our APIs used to only work with lowercase. Not entirely sure if it is still the case everywhere but lets always cast to lowercase with api requests.

2022-10-25 14:28 UTC, b4rtaz commented on packages/common/evmUtils/src/operations/token/getWalletTokenTransfersOperation.ts
> +    address: EvmAddress.create(request.address, core).checksum,
Good point! I've changed it.

2022-10-26 10:08 UTC, sogunshola approved these changes

2022-10-26 14:48 UTC, ErnoW approved these changes

2022-10-26 14:48 UTC, merged