feat: parse server
MoralisWeb3/Moralis-JS-SDK pull request #778
Opened 2022-10-26 09:06 UTC by sogunshola

implement logic for streams parse server plugin

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-10-26 09:29 UTC, b4rtaz requested changes
The logic from the `@moralisweb3/common-streams-utils` package should be moved to the `@moralisweb3/streams` package as Erno recommended.

```
@moralisweb3/streams
|_ /mapping/core/*
|_ /mapping/internal-txs-processor/*
|_ /mapping/logs-processor/*
|_ /mapping/txs-processor/*
```

2022-10-26 10:47 UTC, b4rtaz requested changes
Basically it's OK. I've found a few little things.

2022-10-26 10:47 UTC, b4rtaz commented on packages/client/parseServer/src/streams/processor.ts
> +  const ProvidedSignature = req.headers['x-signature'];
`ProvidedSignature` -> `providedSignature`

2022-10-26 10:47 UTC, b4rtaz commented on packages/client/parseServer/src/streams/processor.ts
> +const InitializeSyncsPlugin = async (parseObject: any, express: Express, apiKey: string, syncs: streamConfig[]) => {
`InitializeSyncsPlugin` -> `initializeSyncsPlugin`

2022-10-26 10:47 UTC, b4rtaz commented on packages/client/parseServer/src/streams/processor.ts
> +    return res.status(200).json({ message: 'ok' });
You may extract this logic to a dedicated file.

2022-10-27 10:52 UTC, b4rtaz requested changes

2022-10-27 10:52 UTC, b4rtaz commented on packages/client/parseServer/src/streams/webbhook.ts
> +export const map = new Map();
The name of this variable doesn't say anything about what is this.

2022-10-28 09:58 UTC, b4rtaz requested changes

2022-10-28 09:58 UTC, b4rtaz commented on packages/parseServer/src/streams/processor.ts
> +export const streamsSync = (parseInstance: any, options: StreamOptions) => {
`parseInstance: any` Can we set here a dedicated type or the parse server doesn't offer TS definitions?

2022-10-28 09:58 UTC, b4rtaz commented on packages/parseServer/src/streams/processor.ts
> +  return webhookRouter(parseInstance, options?.webhookUrl || '/streams', streams);
I would replace the default path to `/webhook` or `/streams-webhook`.

2022-10-28 09:58 UTC, b4rtaz commented on packages/parseServer/src/streams/processor.ts
> +  return webhookRouter(parseInstance, options?.webhookUrl || '/streams', streams);
I think the keyword `webhook` is quite important.

2022-10-28 09:58 UTC, b4rtaz commented on packages/parseServer/src/streams/upsert.ts
> +    Parse.initialize(this.parseObject.config.appId);
Should we initialize the parse server here again? A user could do it in his own code.

2022-10-28 09:58 UTC, b4rtaz commented on packages/parseServer/src/streams/webbhook.ts
> +const prepareUpdate = (updates: Update[], filters: string[], upsertValue: boolean) => {
The `upsertValue` argument is unnecessary. The code above passes always `true`.

2022-10-28 10:40 UTC, sogunshola commented on packages/parseServer/src/streams/upsert.ts
> +    Parse.initialize(this.parseObject.config.appId);
This is the SDK instance.. I'll change `parseObject` to `parseServer` for easier reading

2022-10-28 12:00 UTC, closed without merging