Endpoints and types refactor for evm
MoralisWeb3/Moralis-JS-SDK pull request #787
Opened 2022-11-01 10:26 UTC by ErnoW

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-11-08 08:17 UTC, b4rtaz requested changes
@sogunshola  *Request & *Response types should have same prefix as OperationId (same uppercase lowercase letters). You may run the `yarn gen:client` command for the `@moralisweb3/client-evm-api` and the `@moralisweb3/client-sol-api` packages and check that, the generated clients have correct references.

2022-11-08 08:17 UTC, b4rtaz commented on packages/common/evmUtils/src/operations/nft/getNFTContractMetadataOperation.ts
> +export type GetNftContractMetadataRequest = Camelize<Omit<RequestParams, 'chain' | 'address'>> & {
`GetNftContractMetadataRequest` -> `GetNFTContractMetadataRequest`

2022-11-08 08:53 UTC, Y0moo commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
Shouldn't it be `pair_address` as we have in openapi?

2022-11-08 08:54 UTC, Y0moo commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
I can see some renaming to camelcase across getRequestUrlParams functions. But as I understand params inside should be equal to `query`+`path`?

2022-11-08 08:54 UTC, Y0moo commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
@sogunshola

2022-11-08 09:01 UTC, b4rtaz commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
Good point! The `getRequestUrlParams` should return names using by the API (especially search parameters, url parameters depend on the `urlPathPattern` property).

2022-11-08 09:23 UTC, Y0moo commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
I guess we simply can declare in function returned type `RequestParams`:
```
function getRequestUrlParams(request: GetPairAddressRequest, core: Core) : RequestParams { }
```

2022-11-08 09:53 UTC, Y0moo commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
Maybe make a type `Record<keyof RequestParams, string | undefined>`, but I don't like this approach since it makes code more complicated. I guess it'd be better to put this check to the tests

2022-11-08 10:43 UTC, sogunshola commented on packages/common/evmUtils/src/operations/defi/getPairReservesOperation.ts
> +    pairAddress: EvmAddress.create(request.pairAddress, core).lowercase,
There is a small problem here.
```typescript
public prepareUrl(baseUrl: string, request: Request) {
    const urlParams = this.operation.getRequestUrlParams(request, this.core);

    let urlPath = this.operation.urlPathPattern;

    for (const paramName of this.operation.urlPathParamNames) {
      const paramValue = urlParams[paramName as string];
      if (!paramValue) {
        throw new Error(`Param ${paramName as string} is required`);
      }
      urlPath = urlPath.replace(`{${paramName as string}}`, paramValue as string);
    }
    const url = `${baseUrl}${urlPath}`;

    const urlSearchParams: Record<string, string | string[]> = {};
    Object.keys(urlParams)
      .filter((paramName) => !this.operation.urlPathParamNames.includes(paramName as keyof Request))
      .forEach((paramName) => {
        const paramValue = urlParams[paramName];
        if (paramValue) {
          urlSearchParams[paramName] = paramValue;
        }
      });

    return { url, urlSearchParams };
  }
```

in this logic, the `urlPathParamNames` is `(keyof Request)[]` which has been camelized so the `paramName` searched for in the `urlParams` has to be camelCased as well hence the change to camel case. this is not the case for the search parameters because this logic does not make use of `urlSearchParamNames`. To change this to snake case, we have to change the expected type for `urlPathParamNames`.
@b4rtaz @Y0moo

2022-11-09 08:20 UTC, b4rtaz requested changes

2022-11-09 08:20 UTC, b4rtaz commented on packages/common/evmUtils/src/operations/operations.test.ts
> +        });
I think this is too complicated. You can simplify this:

```ts
 const ignoreBodyCheckOperationNames = ['getContractEvents', 'uploadFolder'];
// ...

if (!ignoreBodyCheckOperationNames.includes(operation.name)) {
        expect(bodyParamNames?.sort().join(',')).toBe(openApiBodyParamNames?.sort().join(','));
}
```

2022-11-09 08:21 UTC, b4rtaz commented on packages/common/evmUtils/src/operations/operations.test.ts
> +        });
We want skip *operations*, not *parameter names*.

2022-11-09 09:18 UTC, b4rtaz approved these changes

2022-11-09 09:23 UTC, merged