Add scenario-based integration tests to auth
MoralisWeb3/Moralis-JS-SDK pull request #801
Opened 2022-11-09 10:05 UTC by Ome-Ananenu

---
Add scenario-based integration tests to auth
about: This contains scenario-based integration tests for auth using the mock server.
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

This contains scenario-based integration tests for auth using the mock server.
Specifically:
- Test scenarios for the request and verify Evm Challenge endpoints.
- Test scenarios for the request and verify Solana Challenge endpoints.

2022-11-09 10:52 UTC, sogunshola requested changes
Looks good 🔥, just a few little corrections

2022-11-09 10:52 UTC, sogunshola commented on packages/auth/integration/test/requestEvmChallenge.test.ts
> +    it('should request evm succesfully', async () => {
```suggestion
    it('should request evm challenge successfully', async () => {
```

2022-11-09 10:52 UTC, sogunshola commented on packages/auth/integration/test/requestEvmChallenge.test.ts
> +    it('should return successfull for depracated network parameters', async () => {
```suggestion
    it('should return successful for deprecated network parameters', async () => {
```

2022-11-09 10:52 UTC, sogunshola commented on packages/auth/integration/test/requestSolanaChallenge.test.ts
> +    it('should request solana succesfully', async () => {
```suggestion
    it('should request solana challenge successfully, async () => {
```

2022-11-09 10:52 UTC, sogunshola commented on packages/auth/integration/test/verifyEvmChallenge.test.ts
> +    it('should request evm succesfully', async () => {
```suggestion
    it('should verify evm challenge successfully, async () => {
```

2022-11-09 10:52 UTC, sogunshola commented on packages/auth/integration/test/verifySolanaChallenge.test.ts
> +    it('should request solana succesfully', async () => {
```suggestion
    it('should verify solana challenge successfully, async () => {
```

2022-11-10 14:15 UTC, b4rtaz requested changes
This is exactly that what we need. Great job! I have only one remark, but this is a small change.

2022-11-10 14:15 UTC, b4rtaz commented on packages/auth/integration/test/requestEvmChallenge.test.ts
> +      expect(result.result.profileId).toEqual('0xbfbcfab169c67072ff418133124480fea02175f1402aaa497daa4fd09026b0e1');
I think it would be better if you would test `.result` property. I think the typed result is more used by users than a raw JSON format. This remark refers to all test.

2022-11-10 14:15 UTC, b4rtaz commented on packages/auth/integration/test/requestEvmChallenge.test.ts
> +    it('should default to evm networkType', async () => {
Missing enter?

2022-11-10 19:06 UTC, Ome-Ananenu commented on packages/auth/integration/test/requestEvmChallenge.test.ts
> +      expect(result.result.profileId).toEqual('0xbfbcfab169c67072ff418133124480fea02175f1402aaa497daa4fd09026b0e1');
Thank you Bart! All changes have been made

2022-11-11 09:58 UTC, merged