Feat/auth refactor
MoralisWeb3/Moralis-JS-SDK pull request #802
Opened 2022-11-09 23:28 UTC by sogunshola

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-11-10 00:16 UTC, FedericoAmura approved these changes

2022-11-14 09:53 UTC, b4rtaz requested changes

2022-11-14 09:53 UTC, b4rtaz commented on packages/auth/src/operations/evm/evmRequestChallengeOperation.ts
> +type OperationId = 'requestChallengeEvm';
The operation id is `requestChallengeEvm`, but the operation is `evmRequestChallengeOperation`. Can we normalize it? Should be `requestChallengeEvmOperation`. This regards to some operations here.

2022-11-15 08:52 UTC, b4rtaz approved these changes

2022-11-15 09:02 UTC, merged