Draft: @moralisweb3/next
MoralisWeb3/Moralis-JS-SDK pull request #824
Opened 2022-11-16 13:59 UTC by Y0moo

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-11-16 16:25 UTC, Y0moo commented
@ErnoW `yarn generate` => `next_readme` to get buggy Handlebard behavior. It cuts 'append' action to "Response" for `useEvmPairAddress`

Expected readme:

```
### Response:

{
  token0: {
    token: Erc20Token;
    blockNumber: string | undefined;
    validated: number | undefined;
    createdAt: Date | undefined;
  };
  token1: {
    token: Erc20Token;
    blockNumber: string | undefined;
    validated: number | undefined;
    createdAt: Date | undefined;
  };
  pairAddress: EvmAddress | undefined;
};
```
Actual result:

```
### Response:
{
  token0: {
    token: Erc20Token;
    blockNumber: string | undefined;
    validated: number | undefined;
    createdAt: Date | undefined;
  };
  token1: {
    token: Erc20Token;
    blockNumber: string | undefined;
    validated: number | undefined;
    createdAt: Date | undefined;
  };
  pairAddress: EvmAddress |
```

2022-11-16 17:05 UTC, Y0moo commented
Deps check will be fixed after https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/825 is merged

2022-11-18 10:45 UTC, b4rtaz requested changes

2022-11-18 10:45 UTC, b4rtaz commented on packages/codegen/src/next/generators/hooks/templates/hook.ts.hbs
> +  const { data, error, mutate, isValidating } = useSWR<{{ names.response }}>(
I would add here:

```
// CAUTION: This file is automatically generated. Do not edit it manually!
```

2022-11-18 10:45 UTC, b4rtaz commented on packages/codegen/src/utils/ModuleGenerator.ts
> +        throw new Error('Not implemented');
```ts
throw new Error(`Not implemented ${this.module}`);
```

 This approach increases errors readability.

2022-11-18 10:45 UTC, b4rtaz commented on packages/codegen/src/utils/OperationFilesParser.ts
> +export class OperationFilesParser extends ModuleGenerator {
Inheritance is passé. [Composition is better](https://betterprogramming.pub/inheritance-vs-composition-2fa0cdd2f939).

2022-11-18 10:45 UTC, b4rtaz commented on packages/common/core/src/Core.ts
> +  }
I think we don't need it. The above layer should know how that, how many times executed the start method.

2022-11-18 10:45 UTC, b4rtaz commented on packages/next/src/MoralisNextApi/RequestHandlerResolver.ts
> +    return new OperationResolver(operation, module.baseUrl, Moralis.Core);
I wonder, how an usage with a pagination look like?

2022-11-18 15:06 UTC, ErnoW requested changes
Very nice work! 🤩
See my comments for some feedback

2022-11-21 08:25 UTC, b4rtaz commented on packages/common/core/src/Core.ts
> +  }
I agree that, it can be valuable for beginners. But basically if you don't know that, if you initialized something or don't, that means you probable have a mess in you project.

2022-11-21 11:03 UTC, Y0moo commented on packages/codegen/src/next/generators/hooks/templates/hook.ts.hbs
> +  const { data, error, mutate, isValidating } = useSWR<{{ names.response }}>(
As I remember we have an agreement that we put all auto-generated files under './generated' folder. So I'm sure if it makes sense to add to each hook

2022-11-21 11:44 UTC, Y0moo commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
What do you think about splitting the interface in the operation like this?:
```
export interface RequestChallengeEvmRequestClient {
  address: EvmAddressish;
  chainId: EvmChainish;
}

export interface RequestChallengeEvmRequestServer extends Camelize<Omit<RequestParams, 'address' | 'chainId' | 'expirationTime' | 'notBefore'>> {
  expirationTime?: DateInput;
  notBefore?: DateInput;
}

export interface RequestChallengeEvmRequest extends RequestChallengeEvmRequestClient, RequestChallengeEvmRequestServer {}
```

2022-11-21 11:50 UTC, b4rtaz commented on packages/codegen/src/next/generators/hooks/templates/hook.ts.hbs
> +  const { data, error, mutate, isValidating } = useSWR<{{ names.response }}>(
Maybe you right. But still I see scenarios when someone opens a hook by "Go to definition" and modifies that file. Of course I can be too hypersensitive for that problem.  😅

2022-11-21 11:52 UTC, Y0moo commented on packages/next/src/MoralisNextApi/RequestHandlerResolver.ts
> +    return new OperationResolver(operation, module.baseUrl, Moralis.Core);
No pagination in this version. Do you mean any possible buggy behavior?

2022-11-21 12:01 UTC, b4rtaz commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
Maybe that part shouldn't be auto-generated. If the client side interface != the backend side interface, and the back-end needs an extra logic to validate an input, that could means, we shouldn't generate it.

Basically that approach is set for the [Firebase auth](https://github.com/MoralisWeb3/firebase-extensions/blob/main/auth/functions/src/index.ts). The backend here also requires an additional logic like creating a token.

2022-11-21 12:06 UTC, Y0moo commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
What do you mean by "that part"? The authentication hooks are not auto-generated. My question is about splitting an interface into two parts so devs can easily see which params are "client" and "server"

2022-11-21 12:06 UTC, b4rtaz commented on packages/next/src/MoralisNextApi/RequestHandlerResolver.ts
> +    return new OperationResolver(operation, module.baseUrl, Moralis.Core);
I wonder what the end-user needs to do, to make a request for a next page. How the code looks like.

```ts
const [cursor, setCursor] = useState(() => null);
const transaction = useEvmTransaction({
    cursor
});

// ...

function onNextClicked() {
    setCursor(...);
}
```

Something like this?

2022-11-21 12:35 UTC, b4rtaz commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
I see. But why you need to use a common type if the hook is not auto-generated? You can use own type dedicated for your layer.

2022-11-21 12:45 UTC, b4rtaz commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
I think the operation approach  is dedicated **ONLY** for one case where the front-end client has the same parameters as the backend proxy. I wouldn't add there a next responsibility.

So that means you cannot use the operation approach for the auth.

For the Firebase you have: 

```[front-end-client] ---(client-backend-interface)---> [backend] ---(operations-interface)---> [operations]```

So the Firebase client side package has own interface to send a data to the backend. That doesn't damages assumptions of the operations approach.

2022-11-21 12:55 UTC, Y0moo commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
I see what you mean. I don't think it's the only time we will face this problem. I proposed a simple way to save us from using the `Omit` generic each time to split the operation's parameters for the client and server.

2022-11-21 13:03 UTC, Y0moo commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
I'm just aware that our authentication types can become outdated if we are not referring to `@moralisweb3/auth` in client-side packages

2022-11-21 13:10 UTC, b4rtaz commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
I see. You try to apply [the DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle. But "[duplication is far cheaper than the wrong abstraction](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction)". Here I think we have a wrong abstraction. Yes, those interfaces are similar (or the first interface is a subset of second one), but this is not a reason why why need to add a new responsibility for the operation approach. Now this approach is super simple and I would keep it.

2022-11-22 05:08 UTC, Y0moo commented on demos/nextjs/app/components/modules/Authentication/Authentication.tsx
> +        timeout: 120,
@ErnoW now these params are set on the server-side in `pages\api\moralis\[...moralis].ts`:
```
import { MoralisNextApi } from '@moralisweb3/next';

export default MoralisNextApi({
  apiKey: process.env.MORALIS_API_KEY,
  authentication: {
    domain: 'amazing.dapp',
    uri: process.env.NEXTAUTH_URL,
    timeout: 120,
  },
});
```

2022-11-22 05:19 UTC, Y0moo commented on packages/next/src/MoralisNextApi/MoralisNextApi.ts
> +async function MoralisNextHandler({ req, res }: MoralisNextHandlerParams) {
I noticed that Next-Auth used this syntax for defining auth resolver and auth providers. 
Example from the docs:

```
/pages/api/auth/[...nextauth].js

import NextAuth from 'next-auth'
import AppleProvider from 'next-auth/providers/apple'
import FacebookProvider from 'next-auth/providers/facebook'
import GoogleProvider from 'next-auth/providers/google'
import EmailProvider from 'next-auth/providers/email'

export default NextAuth({
  providers: [
    // OAuth authentication providers...
    AppleProvider({
      clientId: process.env.APPLE_ID,
      clientSecret: process.env.APPLE_SECRET
    }),
    FacebookProvider({
      clientId: process.env.FACEBOOK_ID,
      clientSecret: process.env.FACEBOOK_SECRET
    }),
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET
    }),
    // Passwordless / email sign in
    EmailProvider({
      server: process.env.MAIL_SERVER,
      from: 'NextAuth.js <no-reply@example.com>'
    }),
  ]
})
```

I didn't find any name conventions for this case. 
We shouldn't lowercase the `MoralisNextAuthProvider` so it follows 'next-auth' namings, but we can lowercase `MoralisNextApi`.

2022-11-22 07:06 UTC, Y0moo commented on packages/next/src/MoralisNextApi/RequestHandlerResolver.ts
> +    return new OperationResolver(operation, module.baseUrl, Moralis.Core);
```
const [cursor, setCursor] = useState(0);
```
Yes, this is the best way to make this atm. Also, I think we should overwrite the `string` types in the SDK to `number` in future.

2022-11-22 07:07 UTC, Y0moo commented on packages/next/src/MoralisNextApi/RequestHandlerResolver.ts
> +    return new OperationResolver(operation, module.baseUrl, Moralis.Core);
because atm simple cursor + 1 will not work that simple, you need to make string number => calculate => string again

2022-11-22 07:11 UTC, Y0moo commented on packages/next/src/MoralisNextApi/RequestHandlerResolver.ts
> +    return new OperationResolver(operation, module.baseUrl, Moralis.Core);
In case we are agree to make pagination options `number` type, we can add simpler way for paginating in @moralisweb3/next

2022-11-23 10:00 UTC, ErnoW approved these changes

2022-11-23 13:06 UTC, merged