Test/evm api[nft] integration tests
MoralisWeb3/Moralis-JS-SDK pull request #839
Opened 2022-11-21 16:40 UTC by Ome-Ananenu

---
name: '[Add scenario-based integration tests to evmApi[nft]'
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Add scenario-based integration tests to evmApi [nft]
(https://gabronickwontdiefromcovid.com/groups/moralis/sdk-squad/-/epics/75)

### Solution Description

Add scenario-based integration tests to evmApi [nft]

2022-11-21 17:26 UTC, FedericoAmura commented on packages/evmApi/integration/mocks/response/evmApiResponse.ts
> +export const createPaginatedEvmApiResponse = (tags: string[], total: number, cursor?: string) => ({
I created the `paginatedResponse.ts` for this kind of responses. Check `getTokenTransferts.ts` to see how to use that

I think that having one wrapper for paginated responses is better than having extras on each response

2022-11-21 17:26 UTC, FedericoAmura commented on packages/evmApi/integration/setup.ts
>  export function cleanEvmApi2() {
Can we also rename this to not have the number 2? Same with `setupEvmApi2`

2022-11-22 09:33 UTC, Ome-Ananenu commented on packages/evmApi/integration/mocks/response/evmApiResponse.ts
> +export const createPaginatedEvmApiResponse = (tags: string[], total: number, cursor?: string) => ({
Thank you Federico...fixed!!

2022-11-22 09:37 UTC, Ome-Ananenu commented on packages/evmApi/integration/setup.ts
>  export function cleanEvmApi2() {
Done!!

2022-11-22 11:58 UTC, b4rtaz requested changes

2022-11-22 11:58 UTC, b4rtaz commented on packages/evmApi/integration/mocks/response/evmApiResponse.ts
> +});
I don't understand why this file is called "evmApiResponse" (very general name) and returns some NFT data.

2022-11-22 12:00 UTC, b4rtaz requested changes

2022-11-22 12:00 UTC, b4rtaz commented on packages/evmApi/integration/mocks/response/nftContractMetadata.ts
> +export const createEvmApiResponse = (tag: string) => ({
This method has too general name too.

2022-11-22 12:00 UTC, b4rtaz commented on packages/evmApi/integration/mocks/response/nftContractMetadata.ts
> +export const createPaginatedEvmApiResponse = (tags: string[], total: number, cursor?: string) => ({
The same.

2022-11-23 06:06 UTC, merged