feat: streams triggers
MoralisWeb3/Moralis-JS-SDK pull request #879
Opened 2022-12-06 15:23 UTC by FedericoAmura

---
name: 'Stream Triggers'
about: This PR adds triggers support for triggers on streams
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-12-13 11:27 UTC, b4rtaz requested changes

2022-12-13 11:27 UTC, b4rtaz commented on packages/common/streamsUtils/src/dataTypes/StreamErc1155Approval/StreamErc1155Approval.ts
> +      triggerResultsB.sort((a, b) => (b.name > a.name ? 1 : -1));
It's better to use `a.localeCompare(b)`.

2022-12-13 11:27 UTC, b4rtaz commented on packages/common/streamsUtils/src/dataTypes/StreamErc20Transfer/StreamErc20Transfer.ts
> +
The same `a.localeCompare(b)`.

2022-12-13 11:27 UTC, b4rtaz commented on packages/common/streamsUtils/src/dataTypes/StreamEvmInternalTransaction/StreamEvmInternalTransaction.ts
> +    }
Again `localeCompare`. I see this section third time. [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)?

2022-12-13 11:27 UTC, b4rtaz commented on packages/common/streamsUtils/src/dataTypes/StreamEvmNftTransfer/StreamEvmNftTransfer.ts
> +    }
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). 💁‍♂️

2022-12-13 11:27 UTC, b4rtaz commented on packages/common/streamsUtils/src/dataTypes/StreamEvmTransaction/StreamEvmTransaction.ts
> +
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). 💁‍♂️

2022-12-13 11:27 UTC, b4rtaz commented on packages/common/streamsUtils/src/dataTypes/StreamEvmTransactionLog/StreamEvmTransactionLog.ts
> +
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). 💁‍♂️

2022-12-13 15:52 UTC, FedericoAmura commented on packages/common/streamsUtils/src/dataTypes/StreamErc1155Approval/StreamErc1155Approval.ts
> +      triggerResultsB.sort((a, b) => (b.name > a.name ? 1 : -1));
I'm using the comparison only to be able to sort them and then compare even if they are out of order.
I wouldn't use localeCompare here because it can have a slow implementation and we don't need any of the locale related stuff

For the DRY comment, I'll change that

2022-12-15 04:59 UTC, ErnoW commented
Looks good. Nice work.

Dont forget to add a changeset entry:

1. Run `yarn changeset` in the root
2. Select affected packages
3. and bump the version with a "minor" bump
4. Then add a human-readable changelog (this will be part of the generated CHANGELOGs)

2022-12-16 02:29 UTC, ErnoW approved these changes

2022-12-16 02:30 UTC, merged