fix: added missing 'normalizeMetadata' param
MoralisWeb3/Moralis-JS-SDK pull request #905
Opened 2022-12-19 14:11 UTC by Y0moo

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

In some places, the parameter "normalizeMetadata" was missing

2022-12-19 14:15 UTC, FedericoAmura approved these changes

2022-12-19 14:23 UTC, b4rtaz requested changes
Not updated *OperationTest.ts files.

2022-12-19 14:56 UTC, b4rtaz commented
@Y0moo haha! 🦅 My eagle eyes see that, there is not a changeset.

2022-12-20 09:07 UTC, b4rtaz approved these changes

2022-12-20 09:17 UTC, merged