Auth MagicLink connector
MoralisWeb3/Moralis-JS-SDK pull request #921
Opened 2022-12-23 19:51 UTC by FedericoAmura

---
name: 'Auth MagicLink connector'
about: This PR adds a connector to use MagicLink in Moralis Client Auth 
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2022-12-27 08:34 UTC, b4rtaz requested changes
Nice work, but I've found a few scratches. The build crashes as well.

I wonder about restoreability of a provider, can I authenticate -> reload page -> restore provider?

2022-12-27 08:34 UTC, b4rtaz commented on packages/client/connector/magicLink/src/MagicLinkEvmConnector.ts
> +    // @ts-ignore
`@ts-ignore` is a very bad practice. It can hide a serious error.

2022-12-27 08:34 UTC, b4rtaz commented on packages/client/connector/magicLink/src/MagicLinkEvmConnector.ts
> +    // @ts-ignore
`@ts-ignore` - bad practice.

2022-12-27 08:34 UTC, b4rtaz commented on demos/webpack/README.md
I don't see updated `demos/webpack/package.json` file. You should add a dependency to the magic link package.

2022-12-27 08:41 UTC, b4rtaz requested changes

2022-12-27 08:41 UTC, b4rtaz commented on demos/webpack/README.md
> +
We could move all secret keys to a `.env` file (+ `.env.example`).

2022-12-27 20:55 UTC, FedericoAmura commented on packages/client/connector/magicLink/src/MagicLinkEvmConnector.ts
> +    // @ts-ignore
They haven't fixed that compatibility, but changing that to an `any` casting as in the Metamask one [(it is also the kind of solution they give)](https://github.com/magiclabs/magic-js/issues/126)

2022-12-27 20:55 UTC, FedericoAmura commented on demos/webpack/README.md
Added

2022-12-27 20:59 UTC, FedericoAmura commented on demos/webpack/README.md
> +
I could not achieve this. However I extracted it to a constant at the top, and made the buttons hide when this is not configured

This is a FE app, so basically there is nothing secret. I know React has env file support but I haven't managed to configure webpack to give us the same feature in this demo. I struggled with several errors trying to get it and don't think this is worth that much time, at least we can consider that as a follow up

2022-12-27 21:18 UTC, b4rtaz requested changes

2022-12-27 21:18 UTC, b4rtaz commented on demos/webpack/README.md
> +
> This is a FE app, so basically there is nothing secret.

This is not a point. This is a demo for customers, so it should be easy to use. Check out our other demos.

2022-12-27 21:18 UTC, b4rtaz commented on packages/client/connector/magicLink/src/MagicLinkEvmConnector.ts
> +    // @ts-ignore
I think casting to `any` is a better solution than `@ts-ignore`. `@ts-ignore` hides obvious errors.

2022-12-28 09:03 UTC, b4rtaz requested changes

2022-12-28 09:03 UTC, b4rtaz commented on packages/client/connector/magicLink/package.json
> +    "@moralisweb3/client-evm-auth": "workspace:^",
There cannot be `workspace:^`. Because if we will publish that package, on a user pc that couldn't be resolved. Here you must put the version from the repo.

2022-12-28 09:03 UTC, b4rtaz commented on demos/webpack/src/main.ts
> +const MAGIC_CONNECT_PUBLISHABLE_API_KEY = '';
It's still a constant. Some tip: you need to install the `dotenv` package to the webpack demo to support the `.env` file.

2022-12-28 12:53 UTC, FedericoAmura commented on demos/webpack/src/main.ts
> +const MAGIC_CONNECT_PUBLISHABLE_API_KEY = '';
Did that, only got more errors and finally got stuck. Tried also with `webpack-dotenv` package and still no success. Gonna try again today with some rest

2022-12-28 12:53 UTC, FedericoAmura commented on packages/client/connector/magicLink/src/MagicLinkEvmConnector.ts
> +    // @ts-ignore
I'm on it. Magic typing system is complex as it is based on extensions. Worst case, I'll have to type it myself

2022-12-28 12:53 UTC, FedericoAmura commented on packages/client/connector/magicLink/package.json
> +    "@moralisweb3/client-evm-auth": "workspace:^",
Missed it. Great catch
Changed

2022-12-28 21:12 UTC, FedericoAmura commented on demos/webpack/src/main.ts
> +const MAGIC_CONNECT_PUBLISHABLE_API_KEY = '';
Fixed this. I could bet I did the same thing yesterday but it didn't worked...

2023-01-02 09:21 UTC, b4rtaz requested changes
I'm not sure that we should add the react demo now. We want to create a react package with dedicated syntax for react (similar to nextjs).

2023-01-02 12:54 UTC, b4rtaz requested changes

2023-01-02 12:54 UTC, b4rtaz commented on demos/webpack/src/main.ts
> +    magicLinkAuthButton.setAttribute('class', 'button');
This `if` is in a wrong place. Because if I won't set the `MAGIC_CONNECT_PUBLISHABLE_API_KEY` variable, and can click at the button and I don't get a feedback that, there is something missing.

2023-01-02 13:55 UTC, FedericoAmura commented
> I'm not sure that we should add the react demo now. We want to create a react package with dedicated syntax for react (similar to nextjs).

Good point. I'll remove it once I'm finished. I added this to be able to debug all this client code anyway

2023-01-02 13:59 UTC, FedericoAmura commented on demos/webpack/src/main.ts
> +    magicLinkAuthButton.setAttribute('class', 'button');
If you don't set `MAGIC_CONNECT_PUBLISHABLE_API_KEY` that button will not be shown because it is added on line 137 `authenticateButtonBar.appendChild(magicLinkAuthButton);` (same with the connect button)

But you are right in the goal, and I'm fixing that too for wallet connect buttons. Probably it will be better if I only disable the buttons and show an alert so users know they can do that. What do you think?

2023-01-02 14:13 UTC, b4rtaz commented on demos/webpack/src/main.ts
> +    magicLinkAuthButton.setAttribute('class', 'button');
I think the best would be to show all buttons and displays an error if the connector is not configured. In this way a user sees all possibilities at start.

2023-01-02 18:36 UTC, FedericoAmura commented on demos/webpack/src/main.ts
> +    magicLinkAuthButton.setAttribute('class', 'button');
Done that way

2023-01-03 10:04 UTC, b4rtaz approved these changes

2023-01-03 12:50 UTC, merged