get user speedynodeapikey if moralis secret is provided
MoralisWeb3/Moralis-JS-SDK pull request #94
Opened 2021-10-28 15:01 UTC by sogunshola

---
name: 'Pull request'
about: Initialize node sdk via moralisSecret & Support enable function by using speedy rpcs
---

## New Pull Request

### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [X] I have made corresponding changes to the documentation
- [X] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2021-11-01 12:41 UTC, sogunshola commented on src/MoralisWalletConnectProvider.js
>  /* global window */
I used the web3 provider, however, I had to pass the chainId in the options to set the right rpcurl.

2021-11-02 12:31 UTC, ErnoW requested changes
Nice work, seems to work mostly as expected 🙌

Please see the comments for feedback.
Also, please update the type definition for the start function

2021-11-02 12:31 UTC, ErnoW commented on src/MoralisCustomProvider.js
> +    if (!chainId) throw new Error(ERROR_CHAINID_MISSING);
We can default to chainId `1` if none is provided. We assume eth-mainnet as default in other places as well. It might be good though to check if the provided chainId is a valid chainId, that is defined in the MORALIS_RPCS

2021-11-02 12:31 UTC, ErnoW commented on scripts/genWeb3API.js
> +
```suggestion
```

2021-11-02 12:31 UTC, ErnoW commented on src/Parse.js
> +      throw new Error(error);
We can throw a more descriptive error here. As this will throw an [object] [object] error.
Maybe something along the lines of `"Could not fetch keys with moralisSecret"`

2021-11-02 12:31 UTC, ErnoW commented on src/Parse.js
> +   * @param {string} moralisSecret Your Moralis Application ID and Server URL. Moralis.start({serverUrl,appId})
```suggestion
   * @param {string} moralisSecret
```

2021-11-02 12:31 UTC, ErnoW commented on src/MoralisWalletConnectProvider.js
> +        throw new Error(error);
Why throwing an error here? Is this needed?
This will fail builds for people who have no dependency on walletconnect

2021-11-02 12:31 UTC, ErnoW commented on src/Parse.js
> +        'Moralis.start warning: to use personal speedy nodes, moralisSecret is required'
```suggestion
        'Moralis.start warning: to use web3 access, moralisSecret is required'
```

2021-11-03 12:03 UTC, ErnoW approved these changes

2021-11-03 12:08 UTC, merged