fix: serialisation nextjs requests
MoralisWeb3/Moralis-JS-SDK pull request #953
Opened 2023-01-09 13:04 UTC by ErnoW

---
name: 'Pull request'
about: A new pull request
---

## New Pull Request

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2023-01-09 13:21 UTC, b4rtaz requested changes

2023-01-09 13:21 UTC, b4rtaz commented on packages/next/src/MoralisNextApi/Modules.ts
> +  }
This could by simplify by using the property promotion feature:

```ts
public constructor(
    public readonly name: string,
    public readonly baseUrl: string,
    public readonly operations: UnknownOperation[],

);
```

2023-01-09 13:21 UTC, b4rtaz commented on packages/next/src/MoralisNextApi/Modules.ts
> +export type UnknownOperation = Operation<unknown, unknown, unknown, unknown>;
Maybe we should move this type to the core package (`packages/common/core/src/operations/Operation.ts`). We have many places in the repo where we define the `UnknownOperation` type.

2023-01-09 13:21 UTC, b4rtaz commented on packages/next/src/MoralisNextApi/MoralisNextApi.ts
> +    const operation = module?.getOperationByName(operationName);
Not needed question mark (`?`).

2023-01-09 13:25 UTC, ErnoW commented on packages/next/src/MoralisNextApi/Modules.ts
> +  }
The interface is better readable when providing these values as object properties (at least when having more than 2). I don't think this syntax works when doing it like that, as far as I know. I want to keep the interface as:
```
{
    name: EvmApi.moduleName,
    baseUrl: Moralis.EvmApi.baseUrl,
    operations: evmOperations as UnknownOperation[],
}
```

2023-01-09 13:25 UTC, ErnoW commented on packages/next/src/MoralisNextApi/Modules.ts
> +export type UnknownOperation = Operation<unknown, unknown, unknown, unknown>;
Good one 👍

2023-01-09 13:40 UTC, b4rtaz submitted a review, later dismissed

2023-01-09 14:12 UTC, FedericoAmura commented on packages/next/src/MoralisNextApi/Modules.ts
> +  constructor({ name, baseUrl, operations }: { name: string; baseUrl: string; operations: UnknownOperation[] }) {
The parameter should be interface Module?
We can use Required<Module> or something similar to not use the class and derive a type

2023-01-09 14:30 UTC, b4rtaz commented on packages/next/src/MoralisNextApi/Modules.ts
> +  constructor({ name, baseUrl, operations }: { name: string; baseUrl: string; operations: UnknownOperation[] }) {
Do you suggest something like?

```ts
interface ModuleDescriptor {
    name: string;
    baseUrl: string;
    operations: UnknownOperation[];
}

class Module {

public constructor(private readonly descriptor: ModuleDescriptor) {

}
```

I think this is better than the current approach. The current approach wastes the memory only for a better readability.

2023-01-09 15:04 UTC, FedericoAmura commented on packages/next/src/MoralisNextApi/Modules.ts
> +  constructor({ name, baseUrl, operations }: { name: string; baseUrl: string; operations: UnknownOperation[] }) {
No, I just wanted to type the constructor input

```
type ModuleType = Required<Module>;

class Module {
    name: string;
    baseUrl: string;
    operations: UnknownOperation[];

    public constructor({ name, baseUrl, operations }: ModuleType) {
        this.name = name;
        this.baseUrl = baseUrl;
        this.operations = operations;
    }
}
```


That approach wouldn't be vulnerable to this?:
```
const descriptor = { name: 'aModule', baseUrl: 'https://myurl.com', operations: [] };
const module = new Module(descriptor);

descriptor.baseUrl = 'https://someOtherUrlThatIsNotReadonly';
// And now the module has a different baseUrl because the `readonly` only affects `descriptor`
```
I would prefer an object to not depend anymore on the things it received in its constructor if possible

2023-01-09 16:20 UTC, ErnoW commented
@b4rtaz @FedericoAmura I continued on fixing another bug, included it in this PR as it relates to the previous discussion.

This change allow us to remove the number of arguments to 2, so I removed the object interface now. I do agree with the suggestion @FedericoAmura to have a typed interface before implementing (but it is not needed anymore now).

See commit https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/953/commits/cf2a8e36e277b543cd61eb9a0d10cb496afbc559 for changes related to the other bug. It is about that we do not account for Nullable/Paginated resolvers. Now we resolve the operations based on the EvmApi/SolApi/Auth definitions so that we have a single source of truth for the resolving logic.

2023-01-10 11:22 UTC, b4rtaz approved these changes

2023-01-12 06:57 UTC, merged

2023-01-17 05:54 UTC, Y0moo commented on packages/next/src/MoralisNextApi/MoralisNextApi.ts
> +    MoralisNextHandler({ req, res, authentication, core: Moralis.Core });
Why do we pass here the "core" argument? The Moralis instance is the same across the whole application, so we can import it into any part of the application instead of passing it as an argument. @ErnoW

2023-01-17 10:54 UTC, ErnoW commented on packages/next/src/MoralisNextApi/MoralisNextApi.ts
> +    MoralisNextHandler({ req, res, authentication, core: Moralis.Core });
It's a better design pattern to include these dependencies as argument (see [Dependency injection](https://en.wikipedia.org/wiki/Dependency_injection))

In this case it does not make too much of a difference as in NextJs we also use directly imported instances of the 'core'. But it's a good habit to include it as a dependency wherever we can. But it results in more predictable code.

This is also why we pass around the `core` instance within all the modules/functions within the SDK.