feat: Moralis Streams in Aptos
MoralisWeb3/Moralis-JS-SDK pull request #989
Opened 2023-01-26 19:53 UTC by FedericoAmura

---
name: 'Support for Aptos Streams'
about: This PR adds support for Moralis Streams in Aptos
---

## New Pull Request

### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ ] I have made corresponding changes to the documentation
- [ ] I have updated Typescript definitions when needed

### Issue Description

Related issue: #`FILL_THIS_OUT`

### Solution Description

2023-01-30 08:36 UTC, ErnoW requested changes

2023-01-30 08:36 UTC, ErnoW commented on packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
> +    expect(() => AptosAddress.create('invalid')).toThrowError('[C0005] Invalid address provided: invalid');
Can we have a few tests for a few addresses similar to a valid address that are invalid? For example invalid length etc.

2023-01-30 08:36 UTC, ErnoW commented on packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
> +  const addresses = [
```suggestion
  const validAddresses = [
```

2023-01-30 08:36 UTC, ErnoW commented on packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
> +  ];
I assume that Aptos addresses are always lowercase? It is not like with EVM that there are different formats (checksum [EIP-55](https://eips.ethereum.org/EIPS/eip-55))

2023-01-30 08:36 UTC, ErnoW commented on packages/common/streamsUtils/package.json
> +    "@moralisweb3/common-aptos-utils": "workspace:^",
Never seen this before, what does it mean, will it pull the version from the workspace? And will it still work when we publish the package, when it has no context of the workspace?

Should we not just use the 2.12.0 versioning, and let changeset handle the versioning?

2023-01-30 08:36 UTC, ErnoW commented on packages/common/streamsUtils/src/operations/aptosStreams/updateStreamStatusAptosOperation.ts
> +// TODO openapi spec has an impossible type for this operation (it should be UNION, not INTERSECTION)
Did you report this issue already?

2023-01-30 08:36 UTC, ErnoW commented on packages/common/streamsUtils/src/operations/evmStreams/deleteStreamEvmOperation.ts
> -  return EvmStream.create(jsonResponse, core);
Why was this change made? It is a breaking change

2023-01-30 08:36 UTC, ErnoW commented on packages/streams/src/methods/addAddress.ts
> +        return aptosFetcher({ ...(options as AddAddressAptosRequest) });
I really dislike the use of `as` here as it can result to Typescript errors. Can we not infer the type based on the provided options (like we do in the `Auth` methods)?

2023-01-30 11:04 UTC, b4rtaz requested changes

2023-01-30 11:04 UTC, b4rtaz commented on packages/common/aptosUtils/package.json
> +  "name": "@moralisweb3/common-aptos-utils",
I'm not sure, but we have a naming convention that the name of network should have 3 characters (`@moralisweb3/evm-utils`, `@moralisweb3/sol-utils`). Should be there `common-apt-utils`?

2023-01-30 14:37 UTC, ErnoW commented on packages/common/aptosUtils/package.json
> +  "name": "@moralisweb3/common-aptos-utils",
The convention of using 3 characters is bad design nherited from v1. I prefer full names. Good point @b4rtaz as we should reconsider the naming as wel in v3. I prefer to have it evm, solana and aptos eventually. We should only deviate from this for long names or when the acronym is used in every day language (like EVM).

For this reason I prefer to use aptos as full name in this PR as well

2023-01-30 15:40 UTC, FedericoAmura commented on packages/common/streamsUtils/src/operations/evmStreams/deleteStreamEvmOperation.ts
> -  return EvmStream.create(jsonResponse, core);
Reverted

2023-01-30 15:42 UTC, FedericoAmura commented on packages/common/streamsUtils/package.json
> +    "@moralisweb3/common-aptos-utils": "workspace:^",
Fixed. It was because of my environment

2023-01-30 17:11 UTC, FedericoAmura commented on packages/common/streamsUtils/src/operations/aptosStreams/getAddressesAptosOperation.ts
> +// TODO temporary fix. The openapi spec says that the response is an array of strings, but the actual response is a paginated array of objects with a single string property called "address"
Fixed

2023-01-30 18:06 UTC, FedericoAmura commented on packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
> +  ];
For what I found and tested, it doesn't care about casing.

2023-01-30 18:08 UTC, FedericoAmura commented on packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
> +    expect(() => AptosAddress.create('invalid')).toThrowError('[C0005] Invalid address provided: invalid');
Added test for too long. Too short completes with leading 0s. There is already an invalid address test. I think that covers all possible cases

2023-01-30 18:08 UTC, FedericoAmura commented on packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
> +  const addresses = [
Renamed

2023-01-30 18:28 UTC, FedericoAmura commented on packages/common/streamsUtils/src/operations/aptosStreams/updateStreamStatusAptosOperation.ts
> +// TODO openapi spec has an impossible type for this operation (it should be UNION, not INTERSECTION)
Fixed

2023-01-31 01:45 UTC, FedericoAmura commented on packages/streams/src/methods/addAddress.ts
> +        return aptosFetcher({ ...(options as AddAddressAptosRequest) });
Agree. Consider that an iteration as I finally arrived at a solution that can work. It still uses `as` but differently and now it also defines the type of response you will get. This way, when you pass `networkType = 'evm'` typescript knows it will return and EvmStream and not make you cast it, removing this cast can work but don't have this feature. The same goes for aptos, and can be extended to solana or other blockchains we will add support

I tried several other approaches but this was the best one by far. Destructuring params make the type system complex. Also, I like more the `<Module>.evm.<endpoint>` approach but that would be a breaking change, I would consider that for next version

2023-01-31 14:37 UTC, b4rtaz approved these changes

2023-02-02 08:21 UTC, ErnoW approved these changes

2023-02-02 08:22 UTC, merged